LayerTwo-Labs/drivechain-frontends

lib/config/dependencies.dart
lib/pages/tabs/withdrawal_tab_page.dart
lib/providers/balance_provider.dart

I like this pattern. It's simple to set up, and simple to use.
Strictly speaking, it's not a provider, because those are added differently, but not sure what else to call it.

introduce provider pattern

---

lib/pages/tabs/bmm_tab_page.dart
lib/pages/tabs/home_page.dart
lib/routing/router.dart
lib/routing/router.gr.dart
lib/rpc/rpc.dart

Loosely based on the existing BMM tab in testchain. Need more RPC data before we can add more here

multi: add BMM tab

---

lib/config/dependencies.dart
lib/pages/tabs/dashboard_tab_page.dart
lib/pages/tabs/withdrawal_tab_page.dart
lib/rpc/rpc.dart
test/dashboard_test.dart
test/mocks/rpc_mock.dart

- rpc+mocks: create RPC mock
- tabs/dashboard: add sidechain balance to dashboard
- tabs/withdrawal: refresh balance after withdrawal creation

introduce test framework to mock rpcs

---

lib/config/dependencies.dart
lib/pages/tabs/dashboard_tab_page.dart
lib/providers/transactions_provider.dart
lib/rpc/rpc.dart
lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sail_ui/lib/sail_ui.dart
packages/sail_ui/lib/widgets/buttons/button.dart
packages/sail_ui/lib/widgets/buttons/toggle.dart
packages/sail_ui/lib/widgets/containers/action_tile.dart
packages/sail_ui/lib/widgets/containers/sail_page.dart
packages/sail_ui/lib/widgets/core/sail_text.dart
packages/sail_ui/lib/widgets/static/static_field.dart
pubspec.lock
pubspec.yaml
test/dashboard_test.dart
test/mocks/rpc_mock.dart

help @torkelrogstad
How can I categorize the transactions correctly? And what data should we show?
- rpc: clean up peg out and send rpc calls
- providers+rpc: add transaction provider
- tabs/dashboard: do quick n dirty transaction list

list transactions in dashboard

---

lib/pages/tabs/bmm_tab_page.dart
lib/rpc/rpc.dart
packages/sail_ui/lib/widgets/buttons/button.dart
packages/sail_ui/lib/widgets/core/sail_snackbar.dart
packages/sail_ui/lib/widgets/static/static_field.dart
test/mocks/rpc_mock.dart

I need some help here, @octobocto!

bmm: add list of attempts

---

lib/pages/tabs/withdrawal_bundle_tab_page.dart

~The rpcs are a bloody mystery though, which is pretty much the only thing this PR lacks. Can't figure them out.~

tabs/withdrawal_bundles: add initial structure

---

lib/config/dependencies.dart
lib/pages/tabs/home_page.dart
lib/pages/tabs/testchain/mainchain/bmm_tab_page.dart
lib/pages/tabs/testchain/mainchain/withdrawal_bundle_tab_page.dart
lib/providers/balance_provider.dart
lib/providers/bmm_provider.dart
lib/rpc/rpc_testchain.dart
pubspec.lock
pubspec.yaml

- pubspec: update dependencies
- providers: dont double wrap error
- provider+tabs/bmm: move mining logic to provider
- tabs/withdrawal_bundle: filter list on search

2023 11 21 search

---

lib/config/dependencies.dart
lib/storage/secure_store.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

no need to store theme preferences in the keychain...

lib/storage: replace flutter secure with shared preferences

---

scripts/download-binaries.sh
scripts/flavorize-windows.sh

1. Fix a minor issue in the flavorize script
2. Replace wget with curl, as Windows 10+ comes with curl by default

Windows build stuff

---

packages/sidesail/lib/app.dart
packages/sidesail/lib/rpc/rpc_ethereum.dart

- scripts: linux support
- sidesail/lib: match on slot, not name
- sidesail/rpc: create ethereum account on launch if none active

compare chains by slot, not name

---

.vscode/settings.json
packages/sidesail/lib/app.dart
packages/sidesail/lib/config/sidechains.dart
packages/sidesail/lib/main.dart
packages/sidesail/lib/routing/router.dart
packages/sidesail/lib/rpc/models/active_sidechains.dart
packages/sidesail/lib/rpc/models/zcash_utxos.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

You would guess adding 84 lines of code takes no time at all, but this took hours. Most time spent with getting the zcash binary to work.
- lib/app: refactor is current chain active
- lib/main: name internal chains same as external ones
- rpc/zcash: fetch all balance, blinded and not
- rpc/active_sidechains: make hashid 1&2 required
- rpc/zcash: match unshielded utxo with zcash rpc
- .vscode: update settings file

div zcash fixes

---

packages/sail_ui/lib/widgets/inputs/large_embedded_input.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

- sail_ui/inputs: add number input option to LargeEmbeddedInput
- providers/zcash: implement melt
- tabs/zcash: implement melt

initial version of melting

---

packages/sidesail/lib/config/dependencies.dart
packages/sidesail/lib/pages/tabs/dashboard_tab_page.dart
packages/sidesail/lib/pages/tabs/home_page.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_shield_page.dart
packages/sidesail/lib/providers/balance_provider.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/providers/transactions_provider.dart
packages/sidesail/lib/routing/router.dart
packages/sidesail/lib/rpc/models/core_transaction.dart
packages/sidesail/lib/rpc/models/utxo.dart
packages/sidesail/lib/rpc/rpc_mainchain.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/dashboard_test.dart
packages/sidesail/test/mocks/rpc_mock_mainchain.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

- tabs/zcash: add deposit nudge if empty balance on initial route
- routing: don't hardcode sidechain name, use name from classes
- tabs/zcash: add initial NOT working cast all code
- tabs/mainchain: list utxos, not transactions
- providers: add cast provider
- rpc/zcash: implement cast to 4 unique addresses
- tabs/zcash: implement cast for single UTXO
- tabs/zcash: implement cast in view

initial version of cast, misc bug fixes

---

packages/sidesail/lib/pages/tabs/home_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_cast_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_shield_page.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/routing/router.dart
packages/sidesail/lib/routing/router.gr.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

- tabs/zcash_shield: remove melt/cast references
- rpc/zcash: remove cast function
- providers/cast: cast bills, not bundles
- tabs/zcash: use bill logic in shield/deshield
- tabs/zcash: add separate melt/cast page

move melt/cast to separate page

---

packages/sidesail/lib/pages/tabs/zcash/zcash_cast_page.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/routing/router.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart

- routing: make cast page default zcash-page
- providers/cast: fix aggressive recreation bug in findBillsForAmount
- tabs/zcash: add pending casts up top

show pending casts

---

packages/sail_ui/lib/widgets/chips/connection_success_chip.dart
packages/sail_ui/lib/widgets/containers/single_value_container.dart
packages/sail_ui/pubspec.lock
packages/sail_ui/pubspec.yaml
packages/sidesail/lib/pages/tabs/home_page.dart
packages/sidesail/lib/pages/tabs/settings/app_settings_tab.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/bmm_tab_page.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/withdrawal_bundle_tab_page.dart
packages/sidesail/lib/providers/bmm_provider.dart
packages/sidesail/lib/rpc/models/core_transaction.dart
packages/sidesail/lib/rpc/models/utxo.dart
packages/sidesail/lib/rpc/rpc.dart
packages/sidesail/lib/rpc/rpc_ethereum.dart
packages/sidesail/lib/rpc/rpc_mainchain.dart
packages/sidesail/lib/rpc/rpc_sidechain.dart
packages/sidesail/lib/rpc/rpc_testchain.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/pubspec.lock
packages/sidesail/pubspec.yaml
packages/sidesail/test/mocks/rpc_mock_mainchain.dart
packages/sidesail/test/mocks/rpc_mock_sidechain.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

Show SC${slot} whenever viewing and moving SBTC. BTC when interacting with mainchain.
Also adds block height for sidechain/parentchain.

Show expected ticker when moving SBTC/BTC. Add block count

---

packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart

- rpc/zcash: show correct balance
- rpc/zcash: show 100+ BTC addresses on one line

show correct zcash-balance

---

packages/sail_ui/lib/widgets/containers/single_value_container.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_shield_deshield_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart
packages/sidesail/lib/providers/balance_provider.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/providers/transactions_provider.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/rpc/models/core_transaction.dart
packages/sidesail/lib/rpc/models/raw_transaction.dart
packages/sidesail/lib/rpc/models/utxo.dart
packages/sidesail/lib/rpc/models/zcash_utxos.dart
packages/sidesail/lib/rpc/rpc.dart
packages/sidesail/lib/rpc/rpc_sidechain.dart
packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/dashboard_test.dart

This PR makes misc connection changes.
For example it refetches the block count every second, to refresh balances quickly.
It also rebuilds the view less aggressively than before. Now it only refetches when the underlying data has changed. Not every time the fetch() function is called.

be smarter about data fetching

---

packages/sidesail/lib/pages/tabs/dashboard_tab_page.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart
packages/sidesail/lib/rpc/rpc_mainchain.dart
packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sidesail/test/mocks/rpc_mock_mainchain.dart

- rpc/mainchain: add send and getnewaddress rpcs
- containers: make receive-action be usable for sidechain and parent
- tabs/mainchain: make it possible to send/receive directly on parent chain

Parent transfer

---

packages/sidesail/lib/rpc/rpc_ethereum.dart
packages/sidesail/lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart

- rpc/eth: fetch block count correctly
- tabs/mainchain: change total eth amount in sync with input field

2024 01 24 eth bugs

---

docker-compose.yml
packages/sidesail/lib/app.dart
packages/sidesail/lib/rpc/models/active_sidechains.dart
packages/sidesail/lib/widgets/containers/tabs/home/side_nav.dart
packages/sidesail/pubspec.lock

- **docker-compose: set correct mainchain params for testchain**
- **tabs: set correct parent chain home**
- **lib: give user balance on startup if regtest**

2024 02 03 infinite lightning

---

.github/workflows/dart.yml
packages/sidesail/macos/Runner.xcodeproj/project.pbxproj
packages/sidesail/macos/Runner/Release.entitlements
packages/sidesail/scripts/build-app.sh
packages/sidesail/scripts/build-linux.sh
packages/sidesail/scripts/build-macos.sh
packages/sidesail/scripts/build-windows.sh
packages/sidesail/scripts/download-binaries.sh

Builds all of the platform x chain matrix, except Windows ZSail. Uploads to artifacts after we've built

ci: add application builds

---

packages/sail_ui/lib/widgets/buttons/button.dart
packages/sail_ui/lib/widgets/containers/sail_column.dart
packages/sail_ui/lib/widgets/core/sail_padding.dart
packages/sail_ui/lib/widgets/static/static_field.dart
packages/sail_ui/pubspec.lock
packages/sidesail/lib/config/dependencies.dart
packages/sidesail/lib/config/sidechains.dart
packages/sidesail/lib/logger.dart
packages/sidesail/lib/providers/balance_provider.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/providers/process_provider.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/rpc/rpc.dart
packages/sidesail/lib/rpc/rpc_config.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/scripts/download-binaries.sh
packages/sidesail/scripts/zside-fetch-params.sh

- **rpc/zcash: add default config values for regtest**
- **sail_ui: linting, use super.key**
- **sail_ui: update pubspec.lock**
- **macos: add CODE_SIGN_IDENTITY to .pbxproj**
- **scripts: download zside params if not present**

update zcash default config values, download params if not present

---

packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/rpc/rpc_zcash.dart

- **providers: less noisy logs**
- **rpc/zcash: call clearbanned every single time blockcount is fetched**

clearbanned offten

---

packages/sidesail/lib/config/sidechains.dart

As per https://github.com/LayerTwo-Labs/zcash-sidechain/commit/9ad570d5cce9790b1ae1df874e83cda5189bdf3a

zcash: update data dirs

---

packages/sidesail/lib/rpc/rpc_zcash.dart

- **rpc/zcash: creat conf file in right path**

use correct path when creating zcash.conf

---

.github/workflows/dart.yml

ci: dont build windows

---

packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

- **sail_ui/page: remove top padding**
- **tabs/setting: remove network configuration**
- **tabs/mainchain/transfer: cap max amount**
- **tabs/zcash: prevent max amount from being negative**
- **tabs/peg: cap max amount of withdraw**
- **tabs/zcash: use fold, not reduce, to handle empty lists**
- **faucet-backend: add new go package**
- **sailui+sidesail: move a bunch of code to sailui**
- **faucet: add web project**
- **scripts: add one for reloading sailui**
- **scripts: add build script**
- **faucet: make text selectable**
- **faucet: swap from/to if external**
- **faucet: list last 1000 transactions**
- **faucet: add toggle to show deposits**
- **faucet/scripts: improve deploy script**
- **faucet: only list deposits**
- **faucet: add IP checks**
- **sail_ui+faucet: revert selectable …

add transactions, improve shielding/deshielding

---

packages/faucet/pubspec.yaml
scripts/deploy.sh

- **pubspec: bump dependencies**
- **rpc/zcash: even less aggressive rpc fetching**
- **faucet: fix colors in input fields**
- **faucet: update pubspec version**
- **faucet/scripts: rename deploy script**

up faucet version

---

faucet-backend/drivechaind/drivechain_test.go
faucet-backend/main.go
packages/sidesail/lib/widgets/containers/chain_overview_card.dart
packages/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart
packages/sidesail/lib/widgets/containers/tabs/home/top_nav.dart

- **sidesail: move balances to bottom nav**
- **faucet/backend: fix tests**

2024 06 20 move to bottom nav

---

packages/sail_ui/assets/svgs/icon_calendar.svg
packages/sail_ui/lib/style/style_values.dart
packages/sail_ui/lib/widgets/components/core_transaction.dart
packages/sail_ui/lib/widgets/components/utxo.dart
packages/sail_ui/lib/widgets/containers/single_value_container.dart
packages/sail_ui/lib/widgets/core/sail_text.dart
packages/sidesail/lib/config/sidechains.dart
packages/sidesail/lib/pages/tabs/sidechain_send_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_bill_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_operation_statuses.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart
packages/sidesail/lib/providers/cast_provider.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/widgets/containers/chain_overview_card.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/dashboard_test.dart

- **sail_ui: remove leading green/yellow icon based on confirmations**
- **zcash/melt: dont ask for how many minutes, do immediately**
- **tabs/zcash: refactor bills to be done sunday-saturday, one each day**
- **move transparent transactions to operation statuses page**
- **multi: less padding**

misc design improvements

---

packages/sidesail/lib/pages/tabs/testchain/mainchain/deposit_withdraw_tab_route.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart
packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart

- **sail_ui: better padding for buttons**
- **zcash/whatsgoingon: add image to explain flow**
- **zcash: add do everything for me button**
- **drivechain-frontend: initial poc BDK-based server**
- **bdk: add TX functionality**
- **server: add btc-buf proxy**
- **multi: refactor drivechain server into standalone package**
- **multi: rework documentation to reflect multi-application nature**
- **faucet-backend: fix linter errors**
- **multi: fix happy little linter issues**
- **drivechain-server: add initial API**
- **Update README.md**
- **tabs/depositwithdraw: pull actions out of modals**

no popup deposit&withdraw

---

packages/faucet/pubspec.lock
packages/sail_ui/pubspec.lock
packages/sail_ui/pubspec.yaml
packages/sidesail/lib/routing/router.dart
packages/sidesail/lib/routing/router.gr.dart
packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
packages/sidesail/pubspec.lock
packages/sidesail/pubspec.yaml

- **sail_ui+sidesail: update dependencies**
- **sidesail/eth/deposit: pop one less modal**

new-hire-dep-buf

---

packages/drivechain_client/lib/service.dart

For the most part, this just proxies gRPC calls for a more ergonomic Dart interface.

drivechain_client: implement existing RPCs

---

packages/drivechain_client/lib/main.dart
packages/drivechain_client/lib/pages/overview_page.dart
packages/drivechain_client/lib/pages/receive_page.dart
packages/drivechain_client/lib/pages/root_page.dart
packages/drivechain_client/lib/pages/send_page.dart
packages/drivechain_client/lib/pages/sidechains_page.dart
packages/drivechain_client/lib/pages/transactions_page.dart
packages/drivechain_client/lib/routing/router.dart
packages/drivechain_client/lib/routing/router.gr.dart
packages/drivechain_client/lib/service.dart
packages/drivechain_client/lib/util/color.dart
packages/drivechain_client/pubspec.lock
packages/drivechain_client/pubspec.yaml

This is mostly just structural, all other than the overview page are just placeholders at this point.

drivechain_client: set up root layout

---

packages/drivechain_client/lib/main.dart
packages/drivechain_client/lib/pages/overview_page.dart
packages/drivechain_client/lib/pages/root_page.dart
packages/drivechain_client/lib/service.dart
packages/drivechain_client/lib/util/color.dart
packages/drivechain_client/pubspec.lock
packages/drivechain_client/pubspec.yaml

Uses a dummy btc price of 50k USD. Let me know if there's stuff I should get from sail_ui instead.
I was also unable to get a bold font with a sail-styled `Text` or `SailText` so I had to resort to `RichText` for some of the labels, which is quite verbose.

drivechain_client: add balances view

---

packages/drivechain_client/lib/pages/overview_page.dart
packages/drivechain_client/lib/util/currencies.dart
packages/drivechain_client/pubspec.lock

Uses space-between on currency rows for more consistent spacing and visual placement
Adds a money2 currency for Satoshi

drivechain_client: adjust balances alignment

---

packages/sail_ui/lib/style/style_values.dart
packages/sail_ui/lib/widgets/core/sail_text.dart
packages/sail_ui/lib/widgets/loading_indicator.dart

pretty much just rename mediumWeight to boldWeight

sailui tweaks

---

packages/sail_ui/lib/sail_ui.dart
packages/sail_ui/lib/style/style_values.dart
packages/sail_ui/lib/widgets/buttons/button.dart
packages/sail_ui/lib/widgets/chips/connection_success_chip.dart
packages/sail_ui/lib/widgets/components/core_transaction.dart
packages/sail_ui/lib/widgets/components/utxo.dart
packages/sail_ui/lib/widgets/containers/expandable_list_entry.dart
packages/sail_ui/lib/widgets/containers/questions.dart
packages/sail_ui/lib/widgets/containers/sail_border.dart
packages/sail_ui/lib/widgets/containers/single_value_container.dart
packages/sail_ui/lib/widgets/loading_indicator.dart
packages/sidesail/lib/pages/tabs/sidechain_explorer_tab_page.dart
packages/sidesail/lib/pages/tabs/testchain/mainchain/bmm_tab_page.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart
packages/sidesail/lib/providers/zcash_provider.dart
packages/sidesail/lib/rpc/rpc_ethereum.dart
packages/sidesail/lib/rpc/rpc_sidechain.dart
packages/sidesail/lib/rpc/rpc_testchain.dart
packages/sidesail/lib/rpc/rpc_zcash.dart
packages/sidesail/lib/widgets/containers/chain_overview_card.dart
packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart
packages/sidesail/test/mocks/rpc_mock_sidechain.dart
packages/sidesail/test/mocks/rpc_mock_zcash.dart

fix sidecghain receiving and sending of negative amounts if fee was greater than utxo size. Also refactor some stuff into a proper components, avoiding duplication.
finally, make everything a tad bit prettier by increasing padding, and adding some icons for confirmed/unconfirmed TXs.

sidesail: fix bugs, make prettier

---

drivechain-server/main.go
drivechain-server/server/server.go

Resolves #228 by moving balance fetching and sync to the server struct.

drivechain-server: move sync + balance fetch to server

---

.github/workflows/dart.yml
packages/drivechain_client/lib/env.dart
packages/drivechain_client/lib/gen/drivechain/v1/drivechain.pbgrpc.dart
packages/drivechain_client/lib/main.dart
packages/drivechain_client/lib/pages/overview_page.dart
packages/drivechain_client/lib/pages/root_page.dart
packages/drivechain_client/lib/routing/router.dart
packages/faucet_client/lib/api/api.dart
packages/faucet_client/lib/app.dart
packages/faucet_client/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pbgrpc.dart
packages/faucet_client/lib/gen/bitcoin/drivechaind/v1/drivechain.pbgrpc.dart
packages/faucet_client/test/api_test.dart
packages/sidesail/lib/main.dart
packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart

This PR
- Adds a step to CI for finding fixable lint-issues
- Fixes a bug in the faucet_client where we crashed on parsing the json response from /listclaims

faucet_client: dont crash on parsing /listclaims response

---

faucet-backend/drivechaind/drivechain.go
faucet-backend/go.mod
faucet-backend/go.sum
faucet-backend/main.go
packages/sail_ui/lib/widgets/components/utxo.dart
packages/sail_ui/lib/widgets/containers/single_value_container.dart

This PR will in faucet:
- make sending work
- make creating a sidechain deposit work
- hide txs with negative amount of confirmations (txs that were replaced I think)
pretty nice

faucet: make deposit and send work

---

faucet-backend/drivechaind/drivechain.go
faucet-backend/main.go
scripts/deploy-faucet.sh

This PR will:
- faucet_backend: filter away txs with 0 amount
- build web in profile-mode

faucet: filter away more txs

---

packages/sail_ui/lib/widgets/buttons/button.dart
packages/sidesail/lib/config/chains.dart
packages/sidesail/lib/pages/tabs/log_page.dart
packages/sidesail/lib/pages/tabs/settings/settings_tab.dart
packages/sidesail/lib/routing/router.gr.dart
packages/sidesail/lib/widgets/containers/daemon_connection_card.dart
packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
packages/sidesail/lib/widgets/containers/tabs/home/top_nav.dart

- sidesail: dont load address forever on fail
- sidesail: add application log page
- clients: make hover button prettier
- sidesail: add toggle button for theme

clients: misc tiny improvements

---

packages/drivechain_client/lib/api.dart
packages/drivechain_client/lib/main.dart
packages/drivechain_client/lib/pages/transactions_page.dart
packages/drivechain_client/lib/providers/transactions_provider.dart
packages/faucet_client/lib/app.dart
packages/sail_ui/lib/extensions/formatting.dart
packages/sail_ui/lib/sail_ui.dart
packages/sail_ui/lib/widgets/components/core_transaction.dart
packages/sail_ui/lib/widgets/components/utxo.dart

In this PR we implement the transaction list. We need _way_ more data from the API, but that'll come later. I also think we need some nice green checkmarks here, to indicate confirmed or not.

drivechain_client: implement transaction list

---

packages/drivechain_client/TODO-L1.md

Add a prioritized TODO-list for bitwindow checked with what we've already completed

add TODO.md

---

drivechain-server/bdk/bdk.go

Solves #257 by replacing xprv/xpub values with `[REDACTED]`

drivechain-server: strip descriptor(s) from error messages

---

packages/drivechain_client/lib/main.dart
packages/drivechain_client/lib/pages/overview_page.dart
packages/drivechain_client/lib/pages/send_page.dart
packages/drivechain_client/linux/flutter/generated_plugin_registrant.cc
packages/drivechain_client/linux/flutter/generated_plugins.cmake
packages/drivechain_client/macos/Flutter/GeneratedPluginRegistrant.swift
packages/drivechain_client/macos/Podfile.lock
packages/drivechain_client/pubspec.lock
packages/drivechain_client/pubspec.yaml
packages/drivechain_client/windows/flutter/generated_plugin_registrant.cc
packages/drivechain_client/windows/flutter/generated_plugins.cmake

This also does some minor adjustments to layouts to allow for narrower window sizes. The 600x700 minimum size has been chosen after testing the layouts at different sizes.

drivechain_client: add window_manager, set minimum window size

---

docker-compose.yml
drivechain-server/config.go

After running `docker compose up mainchain`, run this command to connect to Torkels node: `bitcoin-cli -rpcuser=user -rpcpassword=password -signet addnode drivechain.live:8383 onetry`

new mainchain docker

---

packages/drivechain_client/lib/pages/receive_page.dart
packages/drivechain_client/lib/pages/send_page.dart
packages/drivechain_client/lib/pages/sidechain_activation_management_page.dart
packages/drivechain_client/lib/pages/sidechain_proposal_page.dart
packages/drivechain_client/lib/pages/sidechains_page.dart
packages/drivechain_client/lib/widgets/qt_icon_button.dart

drivechain_client: add tooltips to icon buttons

---

drivechain-server/config.go
packages/drivechain_client/lib/api.dart
packages/drivechain_client/lib/pages/send_page.dart
packages/drivechain_client/lib/pages/sidechains_page.dart
packages/drivechain_client/lib/util/error.dart
packages/drivechain_client/lib/widgets/qt_button.dart
packages/drivechain_client/macos/Podfile.lock
packages/drivechain_client/pubspec.lock
packages/faucet_client/pubspec.lock
packages/sail_ui/pubspec.lock
packages/sidesail/pubspec.lock

For drivechain_client, this PR will:
- improve error messages from API. Extract the grpc.message.
- drivechain_client: flip qtbutton param from enabled to disabled
- update pubspec.lock stuff

prevent depositing on empty fields

---

clients/faucet/lib/api/api.dart
clients/faucet/lib/env.dart
docker-compose.yml
faucet-backend/api/faucet/api_faucet.go
faucet-backend/server/server.go

- **faucet: send api requests to api.drivechain.live**
- **server/faucet: dont panic, initialize map**
- **docker-compose: add fallbackfee to drivechaind**
- **api/faucet: refactor dispensation logic**

faucet: less complex cors, bug fixing in backend

---

clients/bitwindow/lib/widgets/qt_button.dart
clients/bitwindow/lib/widgets/qt_icon_button.dart
clients/sail_ui/lib/widgets/buttons/button.dart
clients/sail_ui/lib/widgets/components/core_transaction.dart
clients/sail_ui/lib/widgets/components/dashboard_group.dart
clients/sail_ui/lib/widgets/containers/single_value_container.dart
clients/sail_ui/lib/widgets/core/sail_snackbar.dart
clients/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart

This feels amazing to press. Something for you Paul, I believe.
https://github.com/user-attachments/assets/f04a1295-3409-43fa-b417-3a43c8c6c289

clients/sail_ui: redesign buttons to have a neat-o 3D-effect

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/servers/api.dart
clients/bitwindow/lib/servers/enforcer_rpc.dart
clients/bitwindow/lib/servers/mainchain_rpc.dart
clients/bitwindow/pubspec.lock
clients/bitwindow/pubspec.yaml
clients/bitwindow/scripts/download-binaries.sh
clients/bitwindow/test/mocks/api_mock.dart
clients/sail_ui/lib/classes/rpc_config.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/pubspec.lock
clients/sail_ui/pubspec.yaml
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_mainchain.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart
clients/sidesail/test/mocks/rpc_mock_mainchain.dart
clients/sidesail/test/mocks/rpc_mock_sidechain.dart
drivechain-server/Justfile
drivechain-server/dial/dial.go
drivechain-server/main.go

- **drivechain-server: fix clean script, make binaries executable**
- **drivechain-server: add correct bitcoind args, create dir if not exists**
- **drivechain-server: retry getting mainchain tip 5 times before exiting**

bitwindow: start all binaries part two

---

clients/bitwindow/Justfile
clients/bitwindow/lib/gen/cusf/mainchain/v1/common.pb.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/common.pbenum.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/common.pbjson.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/validator.pb.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/validator.pbenum.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/validator.pbgrpc.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/validator.pbjson.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/wallet.pb.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/wallet.pbenum.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/wallet.pbgrpc.dart
clients/bitwindow/lib/gen/cusf/mainchain/v1/wallet.pbjson.dart
clients/bitwindow/lib/gen/cusf/sidechain/v1/sidechain.pb.dart
clients/bitwindow/lib/gen/cusf/sidechain/v1/sidechain.pbenum.dart
clients/bitwindow/lib/gen/cusf/sidechain/v1/sidechain.pbgrpc.dart
clients/bitwindow/lib/gen/cusf/sidechain/v1/sidechain.pbjson.dart
clients/bitwindow/lib/gen/google/protobuf/wrappers.pb.dart
clients/bitwindow/lib/gen/google/protobuf/wrappers.pbenum.dart
clients/bitwindow/lib/gen/google/protobuf/wrappers.pbjson.dart
clients/bitwindow/lib/main.dart
clients/bitwindow/lib/servers/enforcer_rpc.dart
drivechain-server/bdk/bdk.go
drivechain-server/dir/dir.go
drivechain-server/main.go

- **clients/bitwindow: gen enforcer proto files, ping it on startup**
- **server: refactor get data dir into package**

start enforcer

---

clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/linux/flutter/generated_plugin_registrant.cc
clients/bitwindow/linux/flutter/generated_plugins.cmake
clients/bitwindow/macos/Flutter/GeneratedPluginRegistrant.swift
clients/bitwindow/macos/Podfile.lock
clients/bitwindow/windows/flutter/generated_plugin_registrant.cc
clients/bitwindow/windows/flutter/generated_plugins.cmake

design see withdrawals in bitwindow. No functionality yet.

bitwindow: see withdrawals

---

clients/bitwindow/lib/pages/overview_page.dart
clients/sail_ui/lib/widgets/containers/sail_dialogs.dart
servers/bitwindow/engines/bitcoind_engine.go

- **bengine: return annotated errors**
- **clients/bitwindow: change size of tables**

super tiny changes

---

clients/bitwindow/lib/pages/overview_page.dart
servers/bitwindow/engines/bitcoind_engine.go
servers/bitwindow/models/opreturns/opreturns.go

Small tweaks and fixes to make the Graffitti Explorer more usable

bitwindow: graffitti improvements

---

clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/providers/blockchain_provider.dart
clients/bitwindow/lib/servers/enforcer_rpc.dart
clients/bitwindow/lib/servers/mainchain_rpc.dart
clients/sail_ui/lib/classes/rpc_connection.dart
servers/bitwindow/api/drivechain/drivechain.go
servers/bitwindow/api/wallet/wallet.go
servers/bitwindow/dial/dial.go
servers/bitwindow/main.go
servers/bitwindow/server/server.go

Turns out connecting to bitcoind at localhost:38332 doesn't work! It MUST have 0.0.0.0:38332. This fixes that. And now everything should work.

bitwindow: better startup managemenet

---

clients/bitwindow/lib/pages/overview_page.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/providers/blockchain_provider.dart
clients/bitwindow/linux/CMakeLists.txt
clients/bitwindow/macos/Runner.xcodeproj/project.pbxproj
clients/bitwindow/macos/Runner/Configs/AppInfo.xcconfig
clients/bitwindow/windows/CMakeLists.txt
clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart
clients/sidesail/lib/widgets/containers/tabs/home/top_nav.dart

- **clients/bitwindow: add correct path on windows, i think**
- **clients/bitwindow: add verification height**
- **clients/sidesail: make zside not crash horribly**

clients: set correct app name on windows

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/servers/enforcer_rpc.dart
clients/bitwindow/lib/servers/mainchain_rpc.dart
clients/bitwindow/macos/Runner/AppDelegate.swift
clients/bitwindow/pubspec.lock
clients/faucet/test/widget_test.dart
clients/sail_ui/lib/classes/node_connection_settings.dart
clients/sail_ui/lib/classes/rpc_config.dart
clients/sail_ui/lib/classes/rpc_connection.dart
servers/bitwindow/go.mod
servers/bitwindow/go.sum

- **sail_ui/nodeconnection: read all conf values from file**
- **bitwindow: set correct default addnode, dont overwrite values from bitcoin.conf**
- **bitwindow/enforcerrpc: set --wallet-auto-create**

bitwindow: more attetmpts at debugging boot issues

---

clients/bitwindow/pubspec.lock
clients/faucet/pubspec.lock
clients/launcher/pubspec.lock
clients/sail_ui/pubspec.lock
clients/sail_ui/pubspec.yaml
clients/sidesail/pubspec.lock

- **build(deps): bump build_runner from 2.4.13 to 2.4.14 in /clients/sail_ui**
- **build(deps): bump shared_preferences in /clients/sail_ui**
- **clients: bump dependencies**

new-year-bump

---

servers/bitwindow/api/drivechain/drivechain.go

drivechain: read title/description of sidechain correctly

---

clients/bitwindow/pubspec.lock
clients/bitwindow/pubspec.yaml
clients/faucet/pubspec.lock
clients/launcher/pubspec.lock
clients/launcher/pubspec.yaml
clients/sail_ui/pubspec.lock
clients/sail_ui/pubspec.yaml
clients/sidesail/pubspec.lock

clients: bump deps

---

clients/launcher/assets/chain_config.json
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/services/wallet_service.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart

- **Revert "clients/sail_ui: fix download concurrency issues in launcher"**
- **launcher: extract enforcer correctly**

launcher: extract binaries better

---

clients/bitwindow/test/test_utils.dart
clients/launcher/assets/chain_config.json
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/config/chains.dart
clients/sidesail/test/mocks/mock_binary.dart

- **launcher: add basic delete logic**
- **launcher: wipe more enforcer suffixes**

launcher: wipe more enforcer suffixes

---

clients/bitwindow/test/mocks/api_mock.dart
clients/launcher/lib/widgets/wallet_button.dart
clients/launcher/lib/widgets/wallet_button_model.dart
clients/launcher/linux/flutter/generated_plugin_registrant.cc
clients/launcher/linux/flutter/generated_plugins.cmake
clients/launcher/macos/Flutter/GeneratedPluginRegistrant.swift
clients/launcher/macos/Podfile.lock
clients/launcher/pubspec.lock
clients/launcher/pubspec.yaml
clients/launcher/windows/flutter/generated_plugin_registrant.cc
clients/launcher/windows/flutter/generated_plugins.cmake
clients/sail_ui/lib/classes/node_connection_settings.dart
clients/sail_ui/lib/classes/rpc_config.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/enforcer_rpc.dart
clients/sail_ui/lib/rpcs/mainchain_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart
clients/sidesail/lib/providers/balance_provider.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_mainchain.dart
clients/sidesail/lib/rpc/rpc_sidechain.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart
clients/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
clients/sidesail/test/mocks/rpc_mock_mainchain.dart
clients/sidesail/test/mocks/rpc_mock_sidechain.dart
clients/sidesail/test/mocks/rpc_mock_zcash.dart

- **clients: add balance functions to all rpcs that have it**
- **sailui: trim args by exact match, not prefix**

clients: ignore duplicate args correctly, get balance in launcher

---

clients/launcher/windows/CMakeLists.txt
clients/launcher/windows/runner/CMakeLists.txt
clients/launcher/windows/runner/Runner.rc
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart

perhaps this fixes the wrong application dir on windows? not sure, don't have a windows machine...

launcher/windows: set APPLICATION_ID to layertwolabs.drivechain_launcher

---

clients/launcher/linux/CMakeLists.txt
clients/launcher/linux/my_application.cc
clients/launcher/macos/Runner.xcodeproj/project.pbxproj
clients/launcher/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
clients/launcher/macos/Runner/Configs/AppInfo.xcconfig
clients/launcher/scripts/flavorize-linux.sh
clients/launcher/scripts/flavorize-macos.sh
clients/launcher/scripts/flavorize-windows.sh
clients/launcher/windows/CMakeLists.txt
clients/launcher/windows/runner/CMakeLists.txt
clients/launcher/windows/runner/Runner.rc
clients/launcher/windows/runner/main.cpp
clients/sail_ui/lib/providers/process_provider.dart

This probably won't change anything, but at the very least it's nice to have the same name on macos and windows.

launcher: attempt to rename drivechain_launcher to launcher

---

clients/launcher/lib/env.dart
clients/launcher/lib/main.dart
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/pages/settings_page.dart
clients/launcher/lib/pages/tools_page.dart
clients/launcher/lib/services/wallet_service.dart
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/launcher/test/mocks/download_manager_mock.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart

On windows the interesting binaries are inside a Release/ folder, unlike other platforms.
In this PR we handle that.

launcher: extract from Release/ directory on windows

---

clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/pages/tools_page.dart
clients/launcher/lib/services/wallet_service.dart
clients/launcher/macos/Podfile.lock
clients/sail_ui/assets/svgs/icon_tab_starters.svg
clients/sail_ui/lib/widgets/containers/tab_bar.dart
clients/sail_ui/lib/widgets/core/sail_svg.dart

- **launcher: dont double-refresh UI**
- **sailui: add starters icon**
- **launcher: update mac spec checksums**

launcher: add starter icon

---

clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/linux/flutter/generated_plugin_registrant.cc
clients/bitwindow/linux/flutter/generated_plugins.cmake
clients/bitwindow/macos/Flutter/GeneratedPluginRegistrant.swift
clients/bitwindow/pubspec.lock
clients/bitwindow/pubspec.yaml
clients/bitwindow/windows/flutter/generated_plugin_registrant.cc
clients/bitwindow/windows/flutter/generated_plugins.cmake
clients/faucet/lib/pages/faucet_page.dart
clients/faucet/pubspec.lock
clients/faucet/pubspec.yaml
clients/launcher/linux/flutter/generated_plugin_registrant.cc
clients/launcher/linux/flutter/generated_plugins.cmake
clients/launcher/macos/Flutter/GeneratedPluginRegistrant.swift
clients/launcher/macos/Podfile.lock
clients/launcher/pubspec.lock
clients/launcher/pubspec.yaml
clients/launcher/windows/flutter/generated_plugin_registrant.cc
clients/launcher/windows/flutter/generated_plugins.cmake
clients/sail_ui/lib/config/binaries.dart
clients/scripts/build-macos.sh

- **launcher: add msix deploy stuff to pubspec**
- **sailui/binaries: delete leftover binary directories recursively**

launcher: debug windows

---

clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/sail_ui/lib/providers/binary_provider.dart

- **sail/binaries: be more liberal in dependency initiation**
- **launcher: light mode fixes**

launcher: allow bitwindow start when enforcer not running

---

clients/bitwindow/test/mocks/api_mock.dart
clients/launcher/lib/pages/overview_page.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/enforcer_rpc.dart
clients/sail_ui/lib/rpcs/mainchain_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_mainchain.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart
clients/sidesail/test/mocks/rpc_mock_mainchain.dart
clients/sidesail/test/mocks/rpc_mock_sidechain.dart
clients/sidesail/test/mocks/rpc_mock_zcash.dart

- **sailui: shutdown binaries with kill if not stopped within 5 secs**
- **launcher: better rpc stop management**

launcher: force kill if not stopped with rpc

---

clients/bitwindow/lib/env.dart
clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/macos/Podfile.lock
clients/faucet/lib/pages/faucet_page.dart
clients/faucet/test/mocks/api_mock.dart
clients/launcher/assets/chain_config.json
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/pages/settings_page.dart
clients/launcher/lib/pages/tools_page.dart
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/launcher/macos/Podfile.lock
clients/sail_ui/lib/classes/node_connection_settings.dart
clients/sail_ui/lib/classes/rpc_config.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/enforcer_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart

This PR further debugs windows issues by changing host parameters to 127.0.0.1. Works on my windows machine!
Also makes the UX smoother here and there. Such as removing errors on startup.

launcher: more windows debugging

---

clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/widgets/welcome_modal.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/enforcer_rpc.dart
clients/sail_ui/lib/rpcs/mainchain_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart
clients/sidesail/lib/rpc/rpc_mainchain.dart

- **launcher: dont close welcome modal when opened manually**
- **launcher: add proper shutdown thingies**
- **sailui/rpc: ping connection timer better**

launcher: even better process management

---

clients/launcher/lib/pages/tools_page.dart

- **launcher: more user friendly modal**
- **launcher: implement advanced tab and clean up settings**
- **launcher: fix lint**
- **launcher: dont crash tools page**

launcher: dont crash tools page

---

clients/launcher/lib/main.dart
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/pages/tools_page.dart
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart

- **launcher: better state management**
- **launcher: remove wipe wallet functionality**

launcher: more state management

---

clients/bitwindow/pubspec.lock
clients/launcher/macos/Podfile.lock
clients/launcher/pubspec.lock
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/providers/process_provider.dart

- **launcher: update pubspec**
- **launcher: wait differently in stop() function**

launcher: longer shutdown timeout

---

clients/sail_ui/lib/config/binaries.dart

depends on the bitcoin-patched PR to be merged

binaries: dont special case core

---

clients/launcher/assets/chain_config.json

I copied and shortened Paul's github description of the current sidechains:
- Add bitnames description
- Update thunder description

Update Launcher L2 descriptions

---

clients/bitwindow/lib/pages/wallet_page.dart
servers/bitwindow/api/bitcoind/bitcoind.go
servers/bitwindow/api/drivechain/drivechain.go
servers/bitwindow/api/misc/misc.go
servers/bitwindow/api/wallet/wallet.go
servers/bitwindow/main.go
servers/bitwindow/server/server.go
servers/bitwindow/service/service.go

- **bitwindow: make server more stable, retry connections on drop**
- **bitwindow: only show generate button if address is empty**

bitwindow: faster and more stable server

---

clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/linux/flutter/generated_plugin_registrant.cc
clients/bitwindow/linux/flutter/generated_plugins.cmake
clients/bitwindow/macos/Flutter/GeneratedPluginRegistrant.swift
clients/bitwindow/pubspec.lock
clients/bitwindow/windows/flutter/generated_plugin_registrant.cc
clients/bitwindow/windows/flutter/generated_plugins.cmake
clients/faucet/pubspec.lock
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/pages/root_page.dart
clients/launcher/lib/services/wallet_service.dart
clients/launcher/lib/widgets/welcome_modal.dart
clients/launcher/linux/flutter/generated_plugin_registrant.cc
clients/launcher/linux/flutter/generated_plugins.cmake
clients/launcher/macos/Flutter/GeneratedPluginRegistrant.swift
clients/launcher/macos/Podfile.lock
clients/launcher/pubspec.lock
clients/launcher/pubspec.yaml
clients/launcher/windows/flutter/generated_plugin_registrant.cc
clients/launcher/windows/flutter/generated_plugins.cmake
clients/sail_ui/pubspec.lock
clients/sail_ui/pubspec.yaml
clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/linux/flutter/generated_plugin_registrant.cc
clients/sidesail/linux/flutter/generated_plugins.cmake
clients/sidesail/macos/Flutter/GeneratedPluginRegistrant.swift
clients/sidesail/pubspec.lock
clients/sidesail/pubspec.yaml
clients/sidesail/windows/flutter/generated_plugin_registrant.cc
clients/sidesail/windows/flutter/generated_plugins.cmake

- **clients: use stdlib for shutting down processes on exit**
- **clients: remove unused packages**

clients: use stdlib for shutdown management

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/widgets/containers/tab_bar.dart

- **rpcconnection: set better error mesasges**
- **bitwindow: sort txs by date, show correct amount in tx list**
- **bitwindow: start enforcer and bitwindow in parallell**
- **bitwindow: add platform menu bar**

bitwindow: add platform menu bar

---

clients/bitwindow/lib/main.dart
clients/launcher/lib/env.dart
clients/launcher/lib/pages/overview_page.dart
clients/launcher/lib/routing/router.gr.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/mocks/mocks.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/providers/blockchain_provider.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/mainchain_rpc.dart
clients/sail_ui/lib/widgets/nav/bottom_nav.dart
clients/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart

this makes everything boot faster

bitwindow+sailui+launcher: wait for header sync before starting enforcer, not IBD

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/lib/widgets/hash_calculator_modal.dart
clients/launcher/assets/chain_config.json
clients/launcher/lib/main.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/pages/log_page.dart
clients/sail_ui/lib/pages/router.gr.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/enforcer_rpc.dart
clients/sail_ui/lib/widgets/containers/sail_card.dart
clients/sail_ui/lib/widgets/containers/sail_dialogs.dart
clients/sidesail/lib/config/dependencies.dart
clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/lib/pages/tabs/settings/settings_tab.dart
clients/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart
servers/bitwindow/engines/bitcoind_engine.go

- **clients: create a much better log page**
- **bitwindow: better sidechain error states**
- **servers/bitwindow: skip more op returns**

clients: add better log page

---

clients/bitwindow/lib/pages/sidechains_page.dart
servers/bitwindow/engines/bitcoind_engine.go

- **bitwindow: make deposit ux better**
- **bitwindow: skip op_nop5 when finding op_returns**

bitwindow: better deposit ux

---

clients/faucet/lib/pages/faucet_page.dart
clients/launcher/lib/pages/overview_page.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/pages/log_page.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/mainchain_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart
clients/sail_ui/lib/sail_ui.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sail_ui/lib/widgets/components/error_component.dart
clients/sail_ui/lib/widgets/core/sail_text.dart
clients/sail_ui/lib/widgets/modals/daemon_settings_modal.dart
clients/sail_ui/lib/widgets/static/static_field.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart

- **rpcconnection+process: actually handle pid exits**
- **clients: better errors**
- **bitwindow: add settings modal**

clients: prettier errors, better process errors

---

clients/bitwindow/lib/pages/wallet/denial_dialog.dart
clients/bitwindow/lib/pages/wallet_page.dart
servers/bitwindow/api/bitwindowd/bitwindowd.go
servers/bitwindow/api/wallet/wallet.go
servers/bitwindow/database/migrations/008_denials_unique.sql
servers/bitwindow/models/deniability/deniability.go

- **servers/bitwindow: let user denial same utxo multiple times**
- **clients/bitwindow: add paranoid/normal buttons**

bitwindow: even more deniability

---

clients/bitwindow/analysis_options.yaml
clients/bitwindow/lib/pages/debug_window.dart
clients/bitwindow/lib/pages/explorer/block_explorer_dialog.dart
clients/bitwindow/lib/pages/merchants/chain_merchants_dialog.dart
clients/bitwindow/lib/pages/message_signer.dart
clients/bitwindow/lib/pages/overview_page.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/sidechain_proposal_page.dart
clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/lib/pages/wallet/bitcoin_uri_dialog.dart
clients/bitwindow/lib/pages/wallet/denial_dialog.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/lib/widgets/hash_calculator_modal.dart
clients/faucet/analysis_options.yaml
clients/faucet/pubspec.lock
clients/faucet/pubspec.yaml
clients/launcher/analysis_options.yaml
clients/launcher/lib/providers/quotes_provider.dart
clients/launcher/lib/widgets/chain_settings_modal.dart
clients/launcher/lib/widgets/welcome_modal.dart
clients/sail_ui/analysis_options.yaml
clients/sail_ui/lib/widgets/buttons/button.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sail_ui/lib/widgets/containers/sail_card.dart
clients/sail_ui/lib/widgets/containers/sail_column.dart
clients/sail_ui/lib/widgets/containers/sail_dialogs.dart
clients/sail_ui/lib/widgets/modals/daemon_settings_modal.dart
clients/sail_ui/lib/widgets/platform_menu.dart
clients/sidesail/analysis_options.yaml

finally have some time for doing this

clients: clean up code here and there

---

clients/bitwindow/lib/pages/debug_window.dart
clients/launcher/lib/pages/overview_page.dart

bitwindow: make console less confusing, remove the dropdown

---

clients/bitwindow/lib/pages/debug_window.dart
clients/sail_ui/lib/widgets/platform_menu.dart
servers/bitwindow/api/enforcer/enforcer.go
servers/bitwindow/engines/bitcoind_engine.go
servers/bitwindow/main.go
servers/bitwindow/server/server.go

stuff can always be made better!

bitwindow: make console even better, add enforcer rpcs

---

clients/bitwindow/lib/widgets/address_list.dart
clients/launcher/analysis_options.yaml
clients/sail_ui/lib/widgets/components/table.dart
servers/bitwindow/api/wallet/wallet.go
servers/bitwindow/database/migrations/009_addressbook_unique.sql
servers/bitwindow/models/addressbook/addressbook.go

automatically save receiving addresses with no label

bitwindow: improve UX for addressbook,

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/pages/explorer/block_explorer_dialog.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/sail_ui/lib/widgets/containers/sail_card.dart

i dont like forcing the user! later this can become a setting

bitwindow: make new window open optional for block explorer and deniability

---

clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/lib/providers/address_book_provider.dart
clients/bitwindow/lib/widgets/address_list.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/rpc/rpc_zcash.dart
servers/bitwindow/api/bitwindowd/bitwindowd.go

- **enforcer: retry connection on boot**
- **bitwindow: improve address book ux**

bitwindow: better addressbook ux

---

clients/bitwindow/lib/main.dart
clients/bitwindow/lib/pages/explorer/block_explorer_dialog.dart
clients/bitwindow/lib/pages/overview_page.dart
clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/lib/providers/blockchain_provider.dart
clients/bitwindow/lib/providers/news_provider.dart
clients/bitwindow/lib/providers/sidechain_provider.dart
clients/bitwindow/lib/providers/transactions_provider.dart
clients/bitwindow/test/test_utils.dart
clients/launcher/lib/main.dart
clients/launcher/lib/pages/overview_page.dart
clients/launcher/test/test_utils.dart
clients/sail_ui/lib/mocks/mocks.dart
clients/sail_ui/lib/providers/blockinfo_provider.dart
clients/sail_ui/lib/sail_ui.dart
clients/sail_ui/lib/widgets/nav/bottom_nav.dart
clients/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart

- **bitwindow: improve address book ux**
- **clients: refactor blockhainprovider into bitwindow**

clients: refactor blockchain provider

---

clients/bitwindow/macos/Flutter/GeneratedPluginRegistrant.swift
clients/bitwindow/pubspec.lock
clients/bitwindow/pubspec.yaml
clients/faucet/pubspec.lock
clients/launcher/pubspec.lock
clients/launcher/pubspec.yaml
clients/sail_ui/pubspec.lock
clients/sail_ui/pubspec.yaml
clients/sidesail/macos/Podfile.lock
clients/sidesail/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
clients/sidesail/pubspec.lock

- **run scripts/reload-sailui.sh**
- **build(deps): bump bip39_mnemonic in /clients/launcher**
- **build(deps): bump file_picker from 6.2.1 to 9.2.1 in /clients/bitwindow**
- **build(deps): bump bip39_mnemonic in /clients/bitwindow**
- **build(deps): bump archive from 3.6.1 to 4.0.5 in /clients/sail_ui**
- **run scripts/reload-sailui.sh**

clients: bump dependencies

---

clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
clients/sidesail/lib/pages/tabs/zcash/zcash_shield_deshield_page.dart
clients/sidesail/lib/providers/cast_provider.dart
clients/sidesail/lib/widgets/containers/tabs/home/top_nav.dart

sidesail/zcash: rip out a bunch of pages from top nav

---

clients/sail_ui/lib/mocks/mocks.dart
clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/rpc_sidechain.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart
clients/sail_ui/lib/rpcs/zcash_rpc.dart
clients/sail_ui/lib/rpcs/zcash_rpc_mock.dart
clients/sidesail/lib/main.dart
clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
clients/sidesail/lib/widgets/containers/dropdownactions/console.dart
clients/sidesail/pubspec.lock
clients/sidesail/pubspec.yaml
clients/sidesail/test/mocks/rpc_mock_sidechain.dart
clients/sidesail/test/mocks/rpc_mock_zcash.dart

console doesnt work yet because the new window doesnt have file access, but the zcash-mock requires it, hmhm

sidesail: add console and menu bar

---

clients/sail_ui/lib/rpcs/bitnames_rpc.dart
clients/sail_ui/lib/rpcs/thunder_rpc.dart

sidesail: use correct endpoints for thunder and bitnames

---

clients/bitwindow/lib/pages/root_page.dart
clients/faucet/lib/pages/root_page.dart
clients/launcher/lib/pages/root_page.dart
clients/sail_ui/lib/rpcs/zcash_rpc_mock.dart
clients/sail_ui/lib/widgets/components/table.dart
clients/sail_ui/lib/widgets/core/sail_text.dart
clients/sail_ui/lib/widgets/nav/top_nav.dart
clients/sidesail/lib/pages/tabs/home_page.dart
clients/sidesail/lib/pages/tabs/sidechain_overview_page.dart
clients/sidesail/lib/widgets/containers/tabs/home/top_nav.dart

not as crash/overflow-prone now

clients: refactor table component

---

clients/bitwindow/lib/pages/sidechain_proposal_page.dart
clients/bitwindow/lib/pages/sidechains_page.dart
clients/bitwindow/lib/pages/wallet_page.dart
clients/bitwindow/lib/widgets/create_multisig_modal.dart
clients/bitwindow/pubspec.lock
clients/faucet/lib/pages/faucet_page.dart
clients/faucet/pubspec.lock
clients/launcher/lib/widgets/wallet_button.dart
clients/launcher/pubspec.lock
clients/sail_ui/lib/widgets/buttons/button.dart
clients/sail_ui/lib/widgets/buttons/toggle_theme_button.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sail_ui/lib/widgets/containers/notification.dart
clients/sail_ui/lib/widgets/containers/questions.dart
clients/sail_ui/lib/widgets/containers/sail_card.dart
clients/sail_ui/lib/widgets/containers/sail_dialogs.dart
clients/sail_ui/lib/widgets/modals/shutdown_modal.dart
clients/sail_ui/lib/widgets/static/static_field.dart
clients/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
clients/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
clients/sidesail/pubspec.lock

more buttons. very soon done, now

sailui/buttons: add a icon variant

---

clients/bitwindow/macos/Runner/DebugProfile.entitlements
clients/bitwindow/macos/Runner/Release.entitlements
clients/sail_ui/lib/providers/process_provider.dart
servers/bitwindow/go.mod
servers/bitwindow/go.sum

- **clients/bitwindow: make bitdrive work**
- **bitwindow: bump btc-buf**

bitdrive+spammylogs

---

clients/bitwindow/lib/providers/blockchain_provider.dart
clients/launcher/lib/pages/tools_page.dart
clients/sail_ui/lib/mocks/mocks.dart
clients/sail_ui/lib/providers/blockinfo_provider.dart
clients/sail_ui/lib/widgets/buttons/toggle_theme_button.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sail_ui/lib/widgets/core/sail_svg.dart
clients/sail_ui/lib/widgets/inputs/dropdown_menu.dart
clients/sail_ui/lib/widgets/inputs/menu_items.dart
clients/sail_ui/lib/widgets/loaders/progress.dart
clients/sail_ui/lib/widgets/nav/bottom_nav.dart

- **clients/sailui: remove leading icon from names**
- **sailui: add progress bar component**

2025 04 09 more components

---

clients/launcher/lib/pages/overview_page.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/providers/process_provider.dart
clients/sail_ui/lib/rpcs/zcash_rpc.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_testchain.dart

turns out some earlier refactoring broke the retry.. not anymore!

clients: improve restart management

---

clients/bitwindow/lib/pages/root_page.dart
clients/bitwindow/lib/providers/sidechain_provider.dart
clients/bitwindow/scripts/download-binaries.sh
clients/launcher/lib/pages/root_page.dart
clients/sail_ui/lib/providers/blockinfo_provider.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sail_ui/lib/widgets/core/sail_text.dart
clients/sail_ui/lib/widgets/loaders/progress.dart
clients/sail_ui/lib/widgets/nav/bottom_nav.dart
clients/sidesail/lib/pages/tabs/home_page.dart

- **clients/bitwindow: stop all processes it started**
- **scripts: build x86, not arm**

bitwindow: stop all processes it started

---

clients/bitwindow/linux/CMakeLists.txt
clients/bitwindow/macos/Runner.xcodeproj/project.pbxproj
clients/bitwindow/macos/Runner/Configs/AppInfo.xcconfig
clients/bitwindow/pubspec.yaml
clients/bitwindow/scripts/flavorize-windows.sh
clients/bitwindow/windows/CMakeLists.txt
clients/bitwindow/windows/runner/Runner.rc
clients/launcher/assets/chain_config.json
clients/sail_ui/lib/config/binaries.dart
servers/bitwindow/dir/dir.go

clients/bitwindow: rename application id to bitwindow

---

.github/workflows/bitwindowd.yml
.vscode/settings.json
clients/bitwindow/lib/main.dart
clients/launcher/lib/pages/overview_page.dart
clients/sail_ui/lib/classes/rpc_connection.dart
clients/sail_ui/lib/config/binaries.dart
clients/sail_ui/lib/providers/binary_provider.dart
clients/sail_ui/lib/rpcs/bitwindow_api.dart
clients/sail_ui/lib/rpcs/zcash_rpc.dart
clients/sail_ui/lib/widgets/components/daemon_connection_card.dart
clients/sidesail/lib/rpc/rpc_ethereum.dart
clients/sidesail/lib/rpc/rpc_testchain.dart
servers/bitwindow/.golangci.yml
servers/bitwindow/Justfile
servers/bitwindow/api/bitcoind/bitcoind.go
servers/bitwindow/api/drivechain/drivechain.go
servers/bitwindow/api/wallet/wallet.go
servers/bitwindow/database/db.go
servers/bitwindow/dial/dial.go
servers/bitwindow/engines/bitcoind_engine.go
servers/bitwindow/logpool/logpool.go
servers/bitwindow/main.go
servers/bitwindow/models/addressbook/addressbook.go
servers/bitwindow/models/blocks/processed_blocks.go
servers/bitwindow/models/deniability/deniability.go

- **servers/bitwindow: add logpool**
- **bitcoind_engine: speed up block sync**
- **clients/bitwindow: show progress bar in daemon connection card**

bitwindow: speed up sync

---

clients/bitwindow/lib/pages/root_page.dart
servers/bitwindow/database/db.go

- **sailui/binaries: debug non-successful asset write**
- **clients/bitwindow: use window manager for shutdown, not built-in flutter**

bitwindow: better shutdown

---

bitwindow/.gitignore
bitwindow/pubspec.lock
faucet/pubspec.lock
launcher/pubspec.lock
sidesail/lib/pages/tabs/ethereum/ethereum_rpc_tab_page.dart
sidesail/lib/rpc/rpc_ethereum.dart
sidesail/pubspec.lock
sidesail/pubspec.yaml

- **bitwindow: add asset/bin to gitignore**

bitwindow: ignore assets/bin in gitignore

---

.github/workflows/build.yml
sail_ui/lib/providers/process_provider.dart

- **sailui/process: decode with systemEncoding.decoder**
- **add more debug logs**
- **ci: go back to old way of doing things**

debug bitcoind exit

---

bitwindow/lib/main.dart
sail_ui/lib/classes/node_connection_settings.dart
sail_ui/lib/providers/process_provider.dart
sail_ui/lib/rpcs/bitnames_rpc.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/mainchain_rpc.dart
sail_ui/lib/rpcs/thunder_rpc.dart

- **bitwindow: dont register SIGTERM on windows**
- **sailui/rpc: add =1 config values with just key**

sailui: read bitcoin conf better

---

.github/workflows/build.yml

ci: better matrix initialization based on changes

---

sail_ui/lib/widgets/nav/bottom_nav.dart
sail_ui/lib/widgets/nav/top_nav.dart
sidesail/lib/pages/tabs/home_page.dart
sidesail/lib/pages/tabs/sidechain_overview_page.dart
sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
sidesail/macos/Podfile.lock

- **sailui/bottomnav: hide blocks if syncing**
- **sailui/topnav: add optional key for active index**
- **sidesail: use new buttons in overview and parent chain tabs**

sidesail: top nav improvements

---

bitwindow/server/main.go
sail_ui/lib/widgets/components/table.dart

- **bitwindow: dont log coreproxy info-logs**
- **sailui/table: allow resizing columns**

allow table resizing

---

.github/workflows/build.yml
.github/workflows/dart.yml
sail_ui/lib/widgets/components/table.dart

- **ci: clear build folder between runs**
- **sailui: dont crash table on first render**

ci: clean build folder between each run

---

bitwindow/server/engines/bitcoind_engine.go
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/mainchain_rpc.dart

- **rpcs: awaait connection in right order**
- **bitwindow: avoid deadlock in sync**

bitwindow: fix sync deadlock

---

bitwindow/lib/providers/sidechain_provider.dart
bitwindow/server/dial/dial.go
bitwindow/server/main.go
bitwindow/server/service/service.go
sail_ui/lib/providers/balance_provider.dart

crypto might be ready when wallet is not, for example

bitwindow/server: dial one enforcer sub-server at a time

---

bitwindow/lib/main.dart
bitwindow/lib/pages/root_page.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/server/api/bitwindowd/bitwindowd.go
bitwindow/server/config.go
bitwindow/server/main.go
bitwindow/server/server/server.go
launcher/lib/main.dart
sail_ui/lib/classes/rpc_connection.dart
sail_ui/lib/config/binaries.dart
sail_ui/lib/providers/binary_provider.dart
sail_ui/lib/rpcs/bitnames_rpc.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/mainchain_rpc.dart
sail_ui/lib/rpcs/thunder_rpc.dart
sail_ui/lib/rpcs/zcash_rpc.dart
sail_ui/lib/widgets/nav/top_nav.dart
thunder/lib/main.dart
zside/lib/main.dart

In this PR we make sure to always rewrite whatever asset is bundled to `assets/bin`.
Prior to this PR, we wrote the asset only once, the first time the user downloaded the program. But that isn't enough!

bitwindow: always rewrite fresh asset

---

bitwindow/lib/pages/wallet/wallet_overview.dart
bitwindow/lib/pages/wallet/wallet_utxos.dart
faucet/.metadata
faucet/lib/pages/explorer_page.dart
faucet/lib/pages/faucet_page.dart
faucet/lib/pages/root_page.dart
faucet/web/index.html
faucet/web/manifest.json
sail_ui/lib/widgets/buttons/button.dart
sail_ui/lib/widgets/components/table.dart
sail_ui/lib/widgets/inputs/menu_items.dart
sail_ui/lib/widgets/nav/top_nav.dart
zside/lib/pages/tabs/zcash/zcash_operation_statuses.dart

First of all this PR makes sure that the faucet doesn't crash. Second it adds "View on mempool" buttons to all relevant tables in bitwindow. Third it makes sure that the users cursor turns into a pointer when a SailButton is hovered over.

faucet: dont crash

---

bitwindow/lib/pages/overview_page.dart
bitwindow/lib/pages/wallet/wallet_send.dart
bitwindow/lib/pages/wallet/wallet_utxos.dart
bitwindow/lib/providers/bitdrive_provider.dart
bitwindow/server/api/wallet/wallet.go
bitwindow/server/engines/bitcoind_engine.go
bitwindow/server/gen/cusf/mainchain/v1/wallet.pb.go
bitwindow/server/gen/wallet/v1/wallet.pb.go
bitwindow/server/models/blocks/processed_blocks.go
bitwindow/server/proto/wallet/v1/wallet.proto
bitwindow/test/mocks/api_mock.dart
sail_ui/lib/gen/cusf/mainchain/v1/wallet.pb.dart
sail_ui/lib/gen/cusf/mainchain/v1/wallet.pbjson.dart
sail_ui/lib/gen/wallet/v1/wallet.pb.dart
sail_ui/lib/gen/wallet/v1/wallet.pbjson.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/widgets/components/table.dart
sail_ui/lib/widgets/containers/sail_card.dart
sail_ui/lib/widgets/containers/sail_dialogs.dart
sail_ui/lib/widgets/containers/tab_bar.dart
sail_ui/lib/widgets/inputs/dropdown_menu.dart

- **bitwindow/blocksyncer: simplify syncing**
- **bitwindow: let user select inputs and send to multiple addresses at once**

bitwindow: better send page

---

bitwindow/lib/widgets/coinnews.dart
bitwindow/pubspec.lock
bitwindow/pubspec.yaml
faucet/pubspec.lock
faucet/pubspec.yaml
launcher/pubspec.lock
launcher/pubspec.yaml
sail_ui/pubspec.lock
sail_ui/pubspec.yaml
thunder/pubspec.lock
thunder/pubspec.yaml
zside/pubspec.lock
zside/pubspec.yaml

- **multi: unbump connectrpc**
- **coinnews: set 3 page size as default**

dump connectrpc

---

bitwindow/pubspec.lock
bitwindow/pubspec.yaml
bitwindow/server/dial/dial.go
faucet/pubspec.lock
faucet/pubspec.yaml
launcher/pubspec.lock
launcher/pubspec.yaml
sail_ui/pubspec.lock
sail_ui/pubspec.yaml
thunder/pubspec.lock
thunder/pubspec.yaml
zside/pubspec.lock
zside/pubspec.yaml

- **bump connectrpc**
- **bitwindow/dial: use shared client with timeouts**

bump connectrpc again

---

bitwindow/server/dial/dial.go
sail_ui/lib/pages/log_page.dart

no longer freeze when opening large files

bitwindow/logpage: make log page more performant

---

bitwindow/lib/widgets/coinnews.dart
sail_ui/lib/widgets/loaders/skeletonizer.dart

gives it less of a coke mouse feel

bitwindow: increase loading duration

---

sail_ui/lib/config/chains.dart
sail_ui/lib/providers/binary_provider.dart
sail_ui/lib/providers/blockinfo_provider.dart
sail_ui/lib/rpcs/thunder_rpc.dart
sail_ui/lib/widgets/containers/sail_dialogs.dart
sail_ui/lib/widgets/core/sail_text.dart
sail_ui/lib/widgets/nav/bottom_nav.dart
sail_ui/lib/widgets/static/static_field.dart
thunder/lib/pages/tabs/sidechain_overview_page.dart
thunder/lib/providers/address_provider.dart

1. **thunder/addressprovider: fetch in timer until both addresses are set**
2. **blockchainprovider: force thunder to stay in aggressive sync**
3. **bottomnav: always notify listeners when blockinfo provider notifies**
Thanks for testing BTCapsule

thunder: ensure address is fetched, update blocks more agressively

---

bitwindow/test/mocks/api_mock.dart
bitwindow/test/test_utils.dart
launcher/lib/main.dart
sail_ui/lib/classes/rpc_connection.dart
sail_ui/lib/config/binaries.dart
sail_ui/lib/mocks/mocks.dart
sail_ui/lib/providers/balance_provider.dart
sail_ui/lib/rpcs/bitnames_rpc.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/mainchain_rpc.dart
sail_ui/lib/rpcs/rpc_sidechain.dart
sail_ui/lib/rpcs/thunder_rpc.dart
sail_ui/lib/rpcs/zcash_rpc.dart
sail_ui/lib/rpcs/zcash_rpc_mock.dart
sail_ui/lib/widgets/components/daemon_connection_card.dart
sail_ui/lib/widgets/nav/bottom_nav.dart
thunder/lib/main.dart
thunder/lib/pages/tabs/home_page.dart
thunder/test/mocks/rpc_mock_sidechain.dart
thunder/test/mocks/rpc_mock_zcash.dart
zside/lib/pages/tabs/home_page.dart
zside/test/mocks/rpc_mock_sidechain.dart
zside/test/mocks/rpc_mock_zcash.dart

thunder: add viewing of logs

---

bitassets/lib/pages/tabs/messaging_page.dart
bitassets/lib/pages/tabs/reserve_register_page.dart
bitassets/pubspec.lock
bitassets/pubspec.yaml
bitnames/lib/pages/tabs/messaging_page.dart
bitnames/lib/pages/tabs/reserve_register_page.dart
bitnames/pubspec.lock
bitnames/pubspec.yaml
sail_ui/lib/widgets/inputs/text_field.dart

turns out the hashes are names hashed with blake3. This PR implements that.

bitnames+assets: use blake3 hashing to/from plaintext names

---

bitassets/lib/pages/tabs/dutch_auction_page.dart
bitassets/lib/pages/tabs/reserve_register_page.dart
bitassets/lib/pages/tabs/wallet_utxos.dart
bitnames/lib/pages/tabs/reserve_register_page.dart
bitnames/lib/pages/tabs/wallet_utxos.dart
bitwindow/lib/pages/debug_window.dart
bitwindow/lib/pages/explorer/block_explorer_dialog.dart
bitwindow/lib/pages/merchants/chain_merchants_dialog.dart
bitwindow/lib/pages/overview_page.dart
bitwindow/lib/pages/sidechain_activation_management_page.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/lib/pages/wallet/denability_page.dart
bitwindow/lib/pages/wallet/denial_dialog.dart
bitwindow/lib/pages/wallet/wallet_hd.dart
bitwindow/lib/pages/wallet/wallet_overview.dart
bitwindow/lib/pages/wallet/wallet_receive.dart
bitwindow/lib/pages/wallet/wallet_utxos.dart
bitwindow/lib/widgets/address_list.dart
bitwindow/lib/widgets/coinnews.dart
faucet/lib/pages/faucet_page.dart
sail_ui/lib/pages/sidechains/sidechain_overview_page.dart
sail_ui/lib/providers/process_provider.dart
sail_ui/lib/widgets/components/table.dart
zside/lib/pages/tabs/sidechain_overview_page.dart
zside/lib/pages/tabs/zcash/zcash_melt_cast_page.dart
zside/lib/pages/tabs/zcash/zcash_operation_statuses.dart
zside/lib/pages/tabs/zcash/zcash_shield_deshield_page.dart
zside/lib/pages/tabs/zcash/zcash_transfer_page.dart

remove all instances of column width

table: resize columns automatically

---

bitwindow/lib/pages/wallet/denability_page.dart
bitwindow/lib/pages/wallet/wallet_send.dart

if a utxo is not in the wallet anymore, it should be automatically be removed

bitwindow: clear stale selected utxos

---

bitwindow/lib/pages/wallet/denability_page.dart
bitwindow/server/api/wallet/wallet.go
bitwindow/server/engines/deniability_engine.go
bitwindow/server/models/deniability/deniability.go
bitwindow/server/models/deniability/deniability_test.go

A historic execution is still denied!

deniability: list correctly by historic executions

---

bitassets/lib/main.dart
bitnames/lib/main.dart
bitwindow/lib/main.dart
bitwindow/lib/pages/explorer/block_explorer_dialog.dart
bitwindow/lib/pages/root_page.dart
bitwindow/lib/providers/bitdrive_provider.dart
bitwindow/lib/providers/blockchain_provider.dart
bitwindow/server/api/bitwindowd/bitwindowd.go
bitwindow/server/api/drivechain/drivechain.go
bitwindow/server/api/enforcer/enforcer.go
bitwindow/server/api/misc/misc.go
bitwindow/server/api/wallet/wallet.go
bitwindow/server/engines/deniability_engine.go
bitwindow/server/service/service.go
launcher/lib/main.dart
launcher/lib/pages/overview_page.dart
launcher/test/test_utils.dart
sail_ui/lib/classes/rpc_connection.dart
sail_ui/lib/logger.dart
sail_ui/lib/mocks/mocks.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/download_manager.dart
sail_ui/lib/providers/binaries/process_manager.dart
sail_ui/lib/providers/sync_provider.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/zcash_rpc.dart
sail_ui/lib/sail_ui.dart
sail_ui/lib/widgets/nav/bottom_nav.dart
thunder/lib/main.dart
zside/lib/main.dart

This PR decreases the log volume by a lot, making sure to still log relevant bits.

clients: less logs

---

bitassets/lib/main.dart
bitnames/lib/main.dart
bitwindow/lib/main.dart
bitwindow/lib/pages/overview_page.dart
bitwindow/lib/pages/sidechains_page.dart
sail_ui/lib/config/binaries.dart
sail_ui/lib/config/sidechains.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/download_manager.dart
sail_ui/lib/rpcs/bitassets_rpc.dart
sail_ui/lib/rpcs/bitnames_rpc.dart
sail_ui/lib/rpcs/thunder_rpc.dart
scripts/lint.sh
thunder/lib/main.dart

lets see what we think of this

poc bitwindow: add launcher INSIDE bitwindow

---

sail_ui/lib/pages/sidechains/parent_chain_page.dart
sail_ui/lib/pages/sidechains/sidechain_overview_page.dart
sail_ui/lib/providers/sidechain/address_provider.dart
sail_ui/lib/widgets/console/console_view.dart

- **console: treat as single arg if inside quote "'**
- **sidechains: show address error if set**

better thunder console, show address errors (if set)

---

bitwindow/lib/main.dart
bitwindow/lib/pages/settings_page.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/lib/providers/wallet_provider.dart
bitwindow/lib/widgets/starters_tab.dart
sail_ui/lib/config/binaries.dart
sail_ui/lib/pages/shutdown_page.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/download_manager.dart
sail_ui/lib/providers/sync_provider.dart
sail_ui/lib/rpcs/bitassets_rpc.dart
sail_ui/lib/rpcs/bitnames_rpc.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart
sail_ui/lib/rpcs/thunder_rpc.dart
sail_ui/lib/rpcs/zcash_rpc.dart
sail_ui/lib/widgets/components/daemon_connection_card.dart
sail_ui/lib/widgets/loaders/progress.dart
sail_ui/lib/widgets/modals/daemon_settings_modal.dart
sail_ui/lib/widgets/nav/bottom_nav.dart

dont hang showing 'nothing' happening after download is complete, but extracting is not. always show something!

bitwindow: better interim download states

---

bitwindow/lib/providers/wallet_provider.dart
bitwindow/macos/Podfile.lock
thunder/pubspec.lock
thunder/pubspec.yaml

We were checking for a non-existent key! No oh no.

bitwindow: dont crash when starting with launcher starter

---

.github/dependabot.yml
Justfile
README.md
bitassets/pubspec.lock
bitassets/pubspec.yaml
bitnames/macos/Podfile.lock
bitnames/pubspec.lock
bitnames/pubspec.yaml
bitwindow/macos/Podfile.lock
bitwindow/pubspec.lock
bitwindow/pubspec.yaml
faucet/pubspec.lock
faucet/pubspec.yaml
sail_ui/pubspec.lock
sail_ui/pubspec.yaml
scripts/reload-sailui.sh
thunder/macos/Podfile.lock
thunder/pubspec.lock
thunder/pubspec.yaml
zside/pubspec.lock
zside/pubspec.yaml

- **build(deps): bump connectrpc from 0.4.0 to 1.0.0 in /sail_ui**
- **build(deps): bump sentry_flutter from 9.1.0 to 9.3.0 in /thunder**
- **build(deps): bump sentry_flutter from 9.1.0 to 9.3.0 in /bitassets**
- **build(deps): bump sentry_flutter from 9.1.0 to 9.3.0 in /bitnames**
- **build(deps): bump skeletonizer from 2.0.1 to 2.1.0+1 in /sail_ui**
- **build(deps): bump sentry_flutter from 9.1.0 to 9.3.0 in /bitwindow**
- **build(deps): bump skeletonizer from 2.0.1 to 2.1.0+1 in /bitwindow**
- **bump connectrpc from 0.4.0 to 1.0.0**

summerbump

---

bitassets/lib/main.dart
bitnames/lib/main.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/lib/pages/wallet/wallet_send.dart
bitwindow/lib/widgets/address_list.dart
sail_ui/lib/config/sidechain_main.dart
sail_ui/lib/providers/window_provider.dart
sail_ui/lib/widgets/containers/sail_card.dart
thunder/lib/main.dart
zside/lib/main.dart
zside/lib/pages/tabs/settings/settings_tab.dart

- **clients: refactor common sidechain-code into a function**
- **bitwindow/sidechains: add 'show only filled' toggle**
- **wallet/send: add address book dropdown**
- **sailui: add 'open in new window' tooltip**

bitwindow: misc improvements

---

bitassets/macos/Podfile.lock
bitassets/pubspec.yaml
bitnames/macos/Podfile.lock
bitnames/pubspec.lock
bitnames/pubspec.yaml
bitwindow/lib/main.dart
bitwindow/lib/pages/overview_page.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/lib/widgets/coinnews.dart
bitwindow/macos/Podfile.lock
bitwindow/pubspec.lock
bitwindow/pubspec.yaml
bitwindow/test/widget_test.dart
faucet/pubspec.lock
faucet/pubspec.yaml
sail_ui/lib/providers/settings_provider.dart
sail_ui/lib/settings/launcher_mode_settings.dart
sail_ui/lib/widgets/components/table.dart
sail_ui/lib/widgets/core/sail_shadow.dart
sail_ui/pubspec.lock
sail_ui/pubspec.yaml
scripts/bump-clients.sh
scripts/reload-sailui.sh
thunder/pubspec.lock
thunder/pubspec.yaml
zside/pubspec.lock
zside/pubspec.yaml

This PR makes tables much better by making them horizontally scrollable. Much more comfy to use.
It also adds the sidechain list front and center on the fireplace, indicating to the user this is something interesting to do.
Finally, it sets the launcher mode to default true, since it seems like it is a path we want to move towards one way or another.

bitwindow: default launcher mode true

---

.github/workflows/build.yml
.gitignore
bitassets/pubspec.lock
bitassets/pubspec.yaml
bitnames/pubspec.yaml
bitwindow/lib/pages/overview_page.dart
bitwindow/pubspec.yaml
scripts/build-app.sh
scripts/build-macos.sh
scripts/build-windows.sh
thunder/pubspec.yaml
zside/pubspec.yaml

- **build: flip order of identity/key path**
- **bitwindow/windows: sign with certificate**

sign with windows certificate

---

.github/workflows/build.yml

cross-the-world uses depreceated images

ci: use yitianyigexiangfa not cross-the-world

---

.github/workflows/build.yml
.gitignore
Justfile
bitassets/Justfile
bitassets/lib/gen/version.dart
bitassets/lib/pages/tabs/settings_page.dart
bitnames/Justfile
bitnames/lib/gen/version.dart
bitnames/lib/pages/tabs/settings_page.dart
bitnames/lib/routing/router.gr.dart
bitwindow/Justfile
bitwindow/lib/gen/version.dart
bitwindow/lib/pages/settings_page.dart
bitwindow/lib/routing/router.gr.dart
faucet/Justfile
faucet/lib/routing/router.gr.dart
sail_ui/Justfile
sail_ui/lib/pages/router.gr.dart
scripts/build-app.sh
scripts/generate-version.sh
scripts/lint.sh
scripts/update-versions.sh
thunder/Justfile
thunder/lib/gen/version.dart
thunder/lib/pages/tabs/settings_page.dart
thunder/lib/routing/router.gr.dart
zside/Justfile
zside/lib/gen/version.dart
zside/lib/pages/tabs/settings/settings_tab.dart
zside/lib/routing/router.gr.dart

responsible for tracking sizes, commit info, release date etc for all of our different binaries

CI: add versions.json file

---

bitassets/scripts/set-app-name.sh
bitnames/scripts/set-app-name.sh
bitwindow/scripts/set-app-name.sh
scripts/build-app.sh
thunder/scripts/set-app-name.sh
zside/scripts/set-app-name.sh

This reverts commit b20906a2a9be0a4667865440bffec205374c454a.

Revert "scripts/build: delete set-app-name.sh"

---

bitassets/pubspec.yaml
bitnames/pubspec.yaml
bitwindow/pubspec.yaml
thunder/pubspec.yaml

clients: set publisher name to LayerTwoLabs

---

.github/workflows/build.yml
.gitignore
bitassets/macos/Runner/Release.entitlements
bitnames/macos/Runner/Release.entitlements
bitwindow/example-appcast.xml
bitwindow/lib/main.dart
bitwindow/macos/Runner/DebugProfile.entitlements
bitwindow/macos/Runner/Release.entitlements
ed25519.priv
scripts/appcast/generate-macos.sh
scripts/appcast/generate-windows.sh
scripts/appcast/get-version.sh
scripts/appcast/merge.sh
thunder/macos/Runner/Release.entitlements
zside/macos/Runner/Release.entitlements

- **clients: add com.apple.security.network.server entitlement to all macos-builds**
- **scripts+bitwindow: add appcast-generation scripts**

bitwindow: add autoupdate

---

sail_ui/lib/config/binaries.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/process_manager.dart

- **binaries: prefer bitwindow-downloaded binaries if present**
- **sailui/binaryprovider: store final err in map**

bitwindow: prefer binaries downloaded from bitwindow if present

---

bitassets/pubspec.lock
bitwindow/lib/main.dart
bitwindow/lib/pages/settings_page.dart
bitwindow/lib/pages/sidechains_page.dart
sail_ui/lib/classes/rpc_connection.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/download_manager.dart
sail_ui/lib/providers/settings_provider.dart

its always launcher mode now:D

multi: rip out launcher mode

---

bitwindow/lib/pages/settings_page.dart
bitwindow/lib/pages/sidechains_page.dart
bitwindow/lib/providers/bitdrive_provider.dart
bitwindow/lib/providers/wallet_provider.dart
bitwindow/server/api/drivechain/drivechain.go
bitwindow/server/api/health/health.go
sail_ui/lib/config/binaries.dart
sail_ui/lib/config/sidechains.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/binaries/download_manager.dart
sail_ui/lib/providers/binaries/process_manager.dart
sail_ui/lib/providers/sync_provider.dart
sail_ui/lib/rpcs/bitassets_rpc.dart
sail_ui/lib/widgets/nav/bottom_nav.dart

- **bitwindow: delete less by being very specific about what we delete**
- **bitwindow: dont hang when downloading binaries**

aug 19 fix

---

bitassets/pubspec.lock
bitassets/pubspec.yaml
bitnames/pubspec.lock
bitnames/pubspec.yaml
bitwindow/pubspec.lock
bitwindow/pubspec.yaml
faucet/pubspec.lock
faucet/pubspec.yaml
sail_ui/pubspec.lock
sail_ui/pubspec.yaml
thunder/pubspec.lock
thunder/pubspec.yaml
zside/pubspec.lock
zside/pubspec.yaml

- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /bitnames**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /thunder**
- **build(deps): bump bitcoin_base from 6.7.0 to 6.8.0 in /bitwindow**
- **build(deps): bump blockchain_utils from 5.1.0 to 5.2.0 in /bitwindow**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /bitassets**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /bitwindow**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /faucet**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /zside**
- **build(deps): bump bitcoin_base from 6.7.0 to 6.8.0 in /bitwindow**
- **build(deps): bump stacked from 3.4.4 to 3.5.0 in /sail_ui**
- **build(deps): bump blockchain_utils from 5.1.0 to 5.2.0 in /bitwindow**
- **build(deps): bump bitcoin_base from 6.7.0 to 6.8.0 in …

flutter: bump deps

---

.github/workflows/build.yml
bitassets/macos/Flutter/GeneratedPluginRegistrant.swift
bitassets/macos/Runner/Info.plist
bitassets/pubspec.lock
bitassets/pubspec.yaml
bitassets/windows/flutter/generated_plugin_registrant.cc
bitassets/windows/flutter/generated_plugins.cmake
bitnames/macos/Flutter/GeneratedPluginRegistrant.swift
bitnames/macos/Runner/Info.plist
bitnames/pubspec.lock
bitnames/pubspec.yaml
bitnames/windows/flutter/generated_plugin_registrant.cc
bitnames/windows/flutter/generated_plugins.cmake
bitwindow/lib/gen/version.dart
scripts/build-macos.sh
thunder/macos/Flutter/GeneratedPluginRegistrant.swift
thunder/macos/Runner/Info.plist
thunder/pubspec.lock
thunder/pubspec.yaml
thunder/windows/flutter/generated_plugin_registrant.cc
thunder/windows/flutter/generated_plugins.cmake
zside/macos/Flutter/GeneratedPluginRegistrant.swift
zside/macos/Runner/Info.plist
zside/pubspec.lock
zside/pubspec.yaml
zside/windows/flutter/generated_plugin_registrant.cc
zside/windows/flutter/generated_plugins.cmake

- **ci: generate pretty .dmg with npm-package**
- **clients: add auto_updater to all clients**

more bitwindow releasing

---

.github/workflows/build.yml
bitwindow/lib/main.dart
bitwindow/pubspec.yaml

- **bitwindow: bump version**
- **ci/bitwindow/snap: extract version more aggressively**

bump bitwindow version

---

bitwindow/lib/env.dart
bitwindow/pubspec.yaml
bitwindow/server/config/config.go
sail_ui/lib/config/binaries.dart
sail_ui/lib/rpcs/bitwindow_api.dart
sail_ui/lib/rpcs/enforcer_rpc.dart

- **bitwindow: change default port to 2122**
- **bitwindow: release new version**

aug 31 change bitwindow port

---

bitwindow/pubspec.yaml
bitwindow/server/database/migrations/015_coin_news_format.sql

We changed the data format! Sorry.

bitwindow: wipe coin news topic, force resync

---

bitwindow/lib/main.dart
bitwindow/lib/pages/settings_page.dart
bitwindow/pubspec.yaml
sail_ui/lib/providers/settings_provider.dart

- **bitwindow: tweak here and there to debug crashing**
- **bitwindow: add error boundary to avoid grey screen**
- **bitwindow: release new version**

bitwindow: debug crashing

---

bitwindow/pubspec.yaml
sail_ui/lib/providers/binaries/process_manager.dart
sail_ui/lib/rpcs/bitwindow_api.dart

- **bitwindow: less crashing, less fucked up logs**

bitwindow: dont crash

---

bitwindow/pubspec.yaml
sail_ui/lib/models/bitcoin_config.dart
sail_ui/lib/providers/bitcoin_conf_provider.dart
sail_ui/lib/widgets/console/integrated_console_view.dart

- **bitwindow: add enforcer alias**
- **bitwindow: add bitcoin-cli alias**
- **bitwindow: release new version**

bitwindow: add enforcer-cli, fix bitcoin-cli

---

bitassets/pubspec.yaml
bitnames/pubspec.yaml
bitwindow/lib/main.dart
bitwindow/lib/pages/settings_page.dart
bitwindow/lib/viewmodels/bitcoin_config_editor_viewmodel.dart
bitwindow/pubspec.yaml
sail_ui/lib/classes/node_connection_settings.dart
sail_ui/lib/classes/rpc_config.dart
sail_ui/lib/config/binaries.dart
sail_ui/lib/mocks/mocks.dart
sail_ui/lib/models/bitcoin_config.dart
sail_ui/lib/providers/binaries/binary_provider.dart
sail_ui/lib/providers/bitcoin_conf_provider.dart
sail_ui/lib/rpcs/mainchain_rpc.dart
sail_ui/lib/sail_app.dart
sail_ui/lib/widgets/console/integrated_console_view.dart
thunder/pubspec.yaml
zside/lib/pages/tabs/settings/settings_tab.dart
zside/pubspec.yaml

- **bitwindow: let user type into configurator**
- **bitwindow: dont override rpcport**
- **bitwindow: prompt for datadir correctly**
- **bitwindow: read rpcport from file, fallback to net default**
- **bitwindow: reload primary color properly on network change**
- **sail_ui: run just format**

bitwindow: even more conf stuff

---

bitassets/pubspec.yaml
bitnames/pubspec.yaml
bitwindow/pubspec.yaml
bitwindow/server/config/config.go
bitwindow/server/database/db.go
sail_ui/lib/providers/bitcoin_conf_provider.dart
thunder/pubspec.yaml
zside/pubspec.yaml

- **bitwindow: add signet-support**
- **bitwindow: dont wipe enforcer or bitwindow data on network change**

bitwindow: use core network to save data
