lib/pages/tabs/withdrawal_tab_page.dart
I think this is clearer? I didn't know what SOC was until I
saw the comment that this commit deletes
=> multi: rename SOC to SBTC

docker/Dockerfile.testchain, docker/build-push-image-testchain.sh
A call to the testchain build script will fetch the most recent master commit, and build that. This ensures that builds will be new every time master updates.
=> dev: update testchain docker image

docker/Dockerfile.mainchain, docker/Dockerfile.testchain, lib/bitcoin.dart, lib/config/sidechains.dart, lib/pages/tabs/testchain/mainchain/bmm_tab_page.dart, lib/pages/tabs/testchain/mainchain/withdrawal_bundle_tab_page.dart, lib/rpc/rpc_testchain.dart, lib/rpc/rpc_withdrawal_bundle.dart, packages/sail_ui/assets/svgs/icon_search.svg, packages/sail_ui/lib/widgets/containers/single_value_container.dart, packages/sail_ui/lib/widgets/core/sail_svg.dart, packages/sail_ui/lib/widgets/inputs/text_field.dart, test/dashboard_test.dart
=> Show current bundle info

docker-compose.yml, lib/pages/tabs/dashboard_tab_page.dart, lib/pages/tabs/ethereum/ethereum_rpc_tab_page.dart, lib/pages/tabs/sidechain_explorer_tab_page.dart, lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart, lib/rpc/rpc_ethereum.dart, lib/widgets/containers/tabs/console.dart, lib/widgets/containers/tabs/dashboard_tab_widgets.dart, lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart, lib/widgets/dialog.dart, packages/sail_ui/lib/widgets/containers/single_value_container.dart
- tabs: change theme when changing coins
- tabs/ethereum: add create account button if none exist
- tabs/console: make ether console slightly better
=> 2023 11 11 more eth

packages/sidesail/lib/pages/tabs/dashboard_tab_page.dart, packages/sidesail/lib/pages/tabs/home_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_shield_deshield_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart, packages/sidesail/lib/providers/transactions_provider.dart, packages/sidesail/lib/routing/router.dart, packages/sidesail/lib/routing/router.gr.dart, packages/sidesail/lib/rpc/rpc_zcash.dart, packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart, packages/sidesail/lib/widgets/containers/tabs/zcash_tab_widgets.dart, packages/sidesail/test/mocks/rpc_mock_zcash.dart
- tabs/zcash: RENAME ONLY
- providers/transactions: better naming of transactions
- rpc/zcash: add sendTransparent and getTransparentAddress functions
- widgets/dashboard: add custom functions for send/receive sidechain-actions
- tabs/zcash: add unique sidechain-transfer page for zcash
- tabs/zcash: separate widget title into it's own viewmodel
=> zcash custom transfer tab

packages/sail_ui/lib/sail_ui.dart, packages/sail_ui/lib/widgets/containers/notification.dart, packages/sidesail/lib/config/dependencies.dart, packages/sidesail/lib/pages/tabs/home_page.dart, packages/sidesail/lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart, packages/sidesail/lib/pages/tabs/testchain/mainchain/withdrawal_bundle_tab_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_melt_cast_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_operation_statuses.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_shield_deshield_page.dart, packages/sidesail/lib/pages/tabs/zcash/zcash_transfer_page.dart, packages/sidesail/lib/providers/balance_provider.dart, packages/sidesail/lib/providers/notification_provider.dart, packages/sidesail/lib/providers/zcash_provider.dart, packages/sidesail/lib/routing/router.dart, packages/sidesail/lib/routing/router.gr.dart, packages/sidesail/lib/rpc/rpc_testchain.dart, packages/sidesail/lib/rpc/rpc_zcash.dart, packages/sidesail/lib/widgets/containers/tabs/dashboard_tab_widgets.dart, packages/sidesail/lib/widgets/containers/tabs/home/side_nav.dart, packages/sidesail/lib/widgets/containers/tabs/home/top_nav.dart, packages/sidesail/lib/widgets/containers/tabs/transfer_mainchain_tab_widgets.dart
- ui: add notification widget
- providers: add notification provider
- tabs/home: show notifications on home page when added
- tabs/mainchaintransfer: stack actions on top of each other
- multi: rename peg to withdraw/deposit
- tabs/zcash: move operation statuses to separate sub-page
- tabs: add optional max amount to send sidechain action
- rpc/zcash: increase fee to allow for many utxo-transactions
- providers/zcash: add notification every time a new operation is added
=> 2024 01 26 more zcash

packages/sidesail/lib/app.dart, packages/sidesail/lib/config/sidechains.dart, packages/sidesail/lib/rpc/models/blockchain_info.dart, packages/sidesail/lib/rpc/rpc.dart, packages/sidesail/lib/rpc/rpc_mainchain.dart, packages/sidesail/lib/rpc/rpc_zcash.dart, packages/sidesail/test/mocks/rpc_mock_mainchain.dart
Issues can occur when starting the sidechain binaries before the mainchain has completed its initial block download. In this PR, we don't start any sidechain binary until IBD is complete, and the mainchain is fully synced. That way, we can be confident all sidechains are activated correctly, and misc other things that's needed to start things gracefully.
It also moves all zcash-configuration to zcash.conf, nothing in the code itself, by writing default values to zcash.conf if it does not exist at startup.
=> Wait for main-IBD to complete before starting sidechain binary

.github/workflows/dart.yml, packages/sidesail/lib/pages/tabs/home_page.dart, packages/sidesail/lib/pages/tabs/testchain/mainchain/deposit_withdraw_tab_route.dart, packages/sidesail/lib/pages/tabs/testchain/mainchain/withdrawal_explorer.dart, packages/sidesail/lib/routing/router.dart, packages/sidesail/lib/routing/router.gr.dart, packages/sidesail/lib/widgets/containers/tabs/home/top_nav.dart
- **pubspec: bump em, and bump em all**
- **delete testchaind from git**
- **rpc/mainchain: move ibd check inside mainchain rpc**
- **tabs/multi: rename send RPC to console**
- **tabs/testchain: make slight changes to withdrawal bundle**
- **config/sidechains: update dir paths for testchain**
- **tabs: replace side nav with only top nav**
- **sail_ui/core: set correct blend mode on svgs**
- **tabs/bmm: make page scrollable**
- **tabs/withdrawal/explorer: move explorer to deposit/withdraw page**
- **ci: dont build windows**
- **ci: reenable windows**
- **tabs/testchain: move withdrawal explorer to separate tab**
=> withdrawal bundle in separate tab

packages/sidesail/lib/providers/bmm_provider.dart, packages/sidesail/lib/rpc/rpc.dart, packages/sidesail/lib/rpc/rpc_ethereum.dart, packages/sidesail/lib/rpc/rpc_mainchain.dart, packages/sidesail/lib/rpc/rpc_sidechain.dart, packages/sidesail/lib/rpc/rpc_testchain.dart, packages/sidesail/lib/rpc/rpc_zcash.dart, packages/sidesail/lib/widgets/containers/tabs/home/bottom_nav.dart, packages/sidesail/pubspec.lock, packages/sidesail/pubspec.yaml, packages/sidesail/test/dashboard_test.dart, packages/sidesail/test/mocks/rpc_mock_mainchain.dart, packages/sidesail/test/mocks/rpc_mock_sidechain.dart, packages/sidesail/test/mocks/rpc_mock_zcash.dart
Prior to this PR, we were very aggressive in fetching the block count. During startup, as fast as we could. After startup, ~3 block count fetchers were started, when only one was needed. That in turn, lead to "work queue depth exceeded".
After this PR, we only start one connection timer per chain. One for mainchain, another for sidechain. Also remove the super-aggressive startup-fetcher. In sum, we are much nicer to the node.
=> less agressive rpcing

packages/drivechain_client/macos/Runner/DebugProfile.entitlements, packages/drivechain_client/macos/Runner/Release.entitlements
Xcode defaults to no outgoing connections for all profiles, this just toggles the app to make HTTP connections as a client.
=> drivechain_client: add necessary macOS entitlements

.vscode/launch.json, packages/drivechain_client/README.md, packages/drivechain_client/lib/env.dart, packages/drivechain_client/lib/main.dart, packages/drivechain_client/lib/service.dart, packages/drivechain_client/pubspec.lock, packages/drivechain_client/pubspec.yaml
Adds a `env.dart` file where all environment config will reside. This adds typed variables and allows for custom variable validation at runtime; useful to weed out config issues before they lead to seemingly unrelated errors. Also adds a launch.json file for Visual Studio Code if useful. If it clutters up the repo without providing real value we can just remove it.
=> drivechain_client: use typed environment variables

faucet-backend/main.go, packages/sidesail/lib/pages/tabs/testchain/mainchain/transfer_mainchain_tab_route.dart, packages/sidesail/lib/providers/cast_provider.dart, packages/sidesail/lib/rpc/rpc_config.dart, packages/sidesail/lib/rpc/rpc_testchain.dart, packages/sidesail/lib/widgets/containers/tabs/deposit_withdraw_tab_widgets.dart
in addition to the title, never exit out of the reset loop in the faucet-backend. it's okay for the drivechain server to err sometimes, but we want to keep the loop alive
=> sail/testchain: include immature balance

packages/drivechain_client/lib/main.dart, packages/faucet/lib/main.dart, packages/sail_ui/lib/sail_app.dart
Would make sense imo, `initMethod` is not used anywhere yet either
=> sail_ui: make `initMethod` optional

drivechain-server/main.go
Resolves #226 by retrieving the common data directory for the runtime OS.
On Linux and macOS, we first look up `XDG_DATA_HOME` before defaulting to the common directories (`$HOME/.local/share` on Linux, `$HOME/Library/Application Support` on macOS).
On Windows, use the `APPDATA` environment variable, this should always be set.
=> drivechain-server: use user-space data directory for bdk-cli data

drivechain-server/buf.yaml, packages/faucet/Justfile, packages/faucet/buf.gen.yaml, packages/faucet/buf.yaml, packages/faucet/lib/api/api.dart, packages/faucet/lib/app.dart, packages/faucet/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pb.dart, packages/faucet/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pbenum.dart, packages/faucet/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pbgrpc.dart, packages/faucet/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pbjson.dart, packages/faucet/lib/gen/bitcoin/bitcoind/v1alpha/bitcoin.pbserver.dart, packages/faucet/lib/gen/bitcoin/drivechaind/v1/drivechain.pb.dart, packages/faucet/lib/gen/bitcoin/drivechaind/v1/drivechain.pbenum.dart, packages/faucet/lib/gen/bitcoin/drivechaind/v1/drivechain.pbgrpc.dart, packages/faucet/lib/gen/bitcoin/drivechaind/v1/drivechain.pbjson.dart, packages/faucet/lib/gen/bitcoin/drivechaind/v1/drivechain.pbserver.dart, packages/faucet/lib/gen/google/protobuf/timestamp.pb.dart, packages/faucet/lib/gen/google/protobuf/timestamp.pbenum.dart, packages/faucet/lib/gen/google/protobuf/timestamp.pbjson.dart, packages/faucet/lib/gen/google/protobuf/timestamp.pbserver.dart, packages/faucet/lib/gen/google/protobuf/wrappers.pb.dart, packages/faucet/lib/gen/google/protobuf/wrappers.pbenum.dart, packages/faucet/lib/gen/google/protobuf/wrappers.pbjson.dart, packages/faucet/lib/gen/google/protobuf/wrappers.pbserver.dart, packages/faucet/lib/providers/transactions_provider.dart, packages/faucet/pubspec.lock, packages/faucet/pubspec.yaml
now that the backend uses btcbuf, the frontend should as well. This adds a buf.yaml file for generating types.
=> faucet: generate types from btcbuf

.github/workflows/dart.yml, .github/workflows/drivechain-server.yml, .github/workflows/faucet-backend.yml, .github/workflows/sidesail.yml
if only faucet_client is changed, only run CI for faucet_client etc.
It feels rather not elegant to include the workflows-repo, but it works wonders
=> ci: only run when changes are made to relevant dir

packages/drivechain_client/lib/pages/send_page.dart, packages/drivechain_client/pubspec.yaml, packages/sail_ui/lib/sail_ui.dart, packages/sail_ui/lib/style/color.dart, packages/sail_ui/lib/widgets/buttons/button.dart, packages/sail_ui/lib/widgets/inputs/checkbox.dart, packages/sail_ui/lib/widgets/inputs/dropdown_menu.dart, packages/sail_ui/lib/widgets/inputs/radio_button.dart, packages/sail_ui/lib/widgets/inputs/text_field.dart
Adds a transaction fee section to the send page and introduces the `stacked` package to manage state in a separate view model instead of in-widget. Tweaks some of the `sail_ui` components to better represent a disabled state.
Also adds a new `SailRadioButton<T>` component for a more Qt/desktop-like radio component.
=> drivechain_client: add transaction fee section, lift state

drivechain-server/api/wallet/wallet.go, drivechain-server/bdk/bdk.go
Previously we would incorrectly return an error if the stored `atomic.Value` was a zero-value struct, this change adds a check and returns the zero-value balance instead.
=> drivechain-server: allow zero-value balance

packages/drivechain_client/lib/api.dart, packages/drivechain_client/lib/pages/overview_page.dart, packages/drivechain_client/lib/pages/send_page.dart, packages/drivechain_client/lib/pages/sidechain_activation_management_page.dart, packages/drivechain_client/lib/pages/sidechain_proposal_page.dart, packages/drivechain_client/lib/pages/sidechains_page.dart, packages/drivechain_client/lib/providers/sidechain_provider.dart, packages/drivechain_client/lib/widgets/qt_button.dart, packages/drivechain_client/lib/widgets/qt_page.dart, packages/sail_ui/lib/sail_ui.dart, packages/sail_ui/lib/widgets/components/table.dart, packages/sail_ui/lib/widgets/inputs/text_field.dart, packages/sail_ui/lib/widgets/inputs/text_form_field.dart
Currently implemented as a dialog as multi-window support is lacking, though it has some downsides that _can_ be mitigated if need be.
Also introduces new sail_ui components; `SailTable` and `SailTextFormField`.
Note: this does not implement the RPC calls to ack, nack and create a sidechain proposal as those are not available yet. The placeholders will need to be updated when these RPCs land.
=> drivechain_client: add sidechain activation management

drivechain-server/.gitignore, drivechain-server/Justfile, drivechain-server/README.md
Convention I guess, just nitpicking. Also adds .mdb folders to .gitignore. Just close if too silly.
=> drivechain-server: (nit) output executables to `/bin` folder

packages/drivechain_client/lib/pages/overview_page.dart, packages/drivechain_client/lib/pages/sidechain_activation_management_page.dart, packages/drivechain_client/lib/pages/sidechains_page.dart, packages/drivechain_client/lib/pages/transactions_page.dart, packages/sail_ui/lib/widgets/components/table.dart
The tables have turned; we're now using `SailTable` everywhere in order to get a uniform look/feel. This change also adds sorting to all tables, hence refactoring simple `DataTable`/`SailTable` subtrees into their own widgets in order to control the sorting state.
This change introduces sorting functionality to `SailTable` very similar to the `DataTable` API.
=> drivechain_client: replace `DataTable` with `SailTable`, add header sorting

.github/workflows/build.yml, clients/scripts/build-macos.sh
For some reason we sometimes get stuck on signing the bip300301-enforcer binary, and here I try to figure out why
=> ci: debug why we cant sign bip300301-enforcer

.github/workflows/build.yml, .github/workflows/drivechain-server.yml, clients/bitwindow/scripts/download-binaries.sh, clients/scripts/build-app.sh, drivechain-server/.gitignore, drivechain-server/Justfile
This PR:
It also
1. Shuffles around where drivechain-server binaries are built to. Now everything is built to drivechain-server/bin.
2. Downloads precompiled binary for bip300301-enforcer from releases.drivechain.info. Prior to this, we downloaded the git folder, and tried to build it ourselves.
3. Bundles all binaries needed for bitwindows to work, that weren't already bundled, e.g: drivechain-server and bdk-cli.
=> ci: bundle part six

clients/bitwindow/lib/main.dart, clients/bitwindow/lib/servers/mainchain_rpc.dart, docker-compose.yml, drivechain-server/api/bitcoind/bitcoind.go, drivechain-server/dial/dial.go, drivechain-server/main.go, drivechain-server/server/server.go
The bip300301-enforcer needs a parameter for where it should create it's database. ./ doesn't quite cut it. When the binary is embedded, it doesn't necessarily have write rights to whereever it's launched. So I need to add that as a param!
=> drivechain-server: add zmqpubsequence and addnode to docker-compose

clients/bitwindow/lib/pages/overview_page.dart, clients/bitwindow/lib/pages/sidechains_page.dart, clients/bitwindow/lib/pages/wallet_page.dart, clients/sail_ui/lib/style/color_scheme.dart, clients/sail_ui/lib/widgets/containers/sail_card.dart, clients/sail_ui/lib/widgets/containers/sail_dialogs.dart, clients/sail_ui/lib/widgets/core/sail_text.dart
better UX! Allows us to more explanations.
One day I will make zcash download correct binaries..
=> clients/bitwindow: add subtitle to all cards

servers/bitwindow/Justfile, servers/bitwindow/main.go
I thought the root cause #448 was to be found here, but that turned out to be false. Anyways, makes sure we write pretty, non-colorized logs to file.
=> bitwindow: write non-colorized, pretty-printed logs to file

clients/sail_ui/lib/config/binaries.dart, clients/sail_ui/lib/providers/binary_provider.dart
The problem occurs in the downloadAndExtract method of the Binary class. Here's what's happening:
The error occurs when trying to extract a zip file, with the error message indicating the zip file doesn't exist at the expected path.
The critical section is in the _setupDirectories and _download methods:
_setupDirectories creates the downloads directory and sets up the zip file path
_download downloads the file to this path
The issue appears to be a race condition where multiple concurrent downloads are trying to:
Create/clean the same downloads directory
Download and write to files in this shared directory
Extract files from this shared directory
The problem is that the cleanup operation at the end of a successful download deletes the entire downloads directory, which could affect other …
=> clients/sail_ui: fix download concurrency issues in launcher

clients/bitwindow/pubspec.lock, clients/bitwindow/pubspec.yaml, clients/faucet/pubspec.lock, clients/launcher/pubspec.lock, clients/launcher/pubspec.yaml, clients/sail_ui/pubspec.lock, clients/sail_ui/pubspec.yaml, clients/sidesail/pubspec.lock, clients/sidesail/pubspec.yaml
- **build(deps): bump build_runner in /clients/bitwindow**
- **build(deps): bump synchronized in /clients/bitwindow**
- **build(deps): bump synchronized in /clients/launcher**
- **build(deps): bump build_runner in /clients/launcher**
- **build(deps): bump build_runner from 2.4.14 to 2.4.15 in /clients/sail_ui**
- **build(deps): bump http from 1.2.2 to 1.3.0 in /clients/sail_ui**
- **build(deps): bump synchronized from 3.3.0+3 to 3.3.1 in /clients/sail_ui**
- **build(deps): bump build_runner in /clients/sidesail**
- **bump deps**
=> 2025 02 17 deps

.github/workflows/build.yml, scripts/build-windows.sh
Fixes a bug where sentry wouldn't build on macos: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
=> ci: allow long ptahs

bitwindow/lib/pages/root_page.dart, bitwindow/lib/pages/sidechains_page.dart, bitwindow/lib/pages/wallet/wallet_receive.dart, bitwindow/lib/providers/blockchain_provider.dart, bitwindow/lib/providers/sidechain_provider.dart, bitwindow/server/api/health/health.go, bitwindow/server/gen/health/v1/health.pb.go, bitwindow/server/gen/health/v1/healthv1connect/health.connect.go, bitwindow/server/proto/health/v1/health.proto, bitwindow/test/mocks/api_mock.dart, sail_ui/lib/classes/rpc_connection.dart, sail_ui/lib/gen/health/v1/health.connect.client.dart, sail_ui/lib/gen/health/v1/health.connect.spec.dart, sail_ui/lib/gen/health/v1/health.pb.dart, sail_ui/lib/gen/health/v1/health.pbjson.dart, sail_ui/lib/gen/health/v1/health.pbserver.dart, sail_ui/lib/mocks/mocks.dart, sail_ui/lib/rpcs/bitwindow_api.dart, sail_ui/lib/rpcs/enforcer_rpc.dart, sail_ui/lib/rpcs/mainchain_rpc.dart
Bitwindow starts before the enforcer and bitcoind is ready. Because of that, the UI tries to fetch addresses+transactions lists etc. before the backend is ready.
Prior to this PR, the user got stuck with an error message "enforcer not available".
In this PR, we listen to bitwindows health stream, and tries to refetch data every time the health status changes. If bitwindow goes from "enforcer not available" --> "available", all components requiring data from the enforcer will attempt a refresh.
=> bitwindow: refetch misc stuff on health status change

bitwindow/lib/pages/sidechains_page.dart, bitwindow/lib/pages/wallet/wallet_send.dart, bitwindow/server/engines/bitcoind_engine.go, sail_ui/lib/rpcs/mainchain_rpc.dart
bitwindow tries to sync 30 blocks in parallell. when it does, it kind of overloads bitcoin core when it has default settings. This increases parallellity by setting
```
-rpcthreads=40
-rpcworkqueue=100
```
=> bitwindow/mainchain: increase rpcthreads

bitassets/pubspec.lock, bitassets/pubspec.yaml, bitnames/pubspec.lock, bitnames/pubspec.yaml, bitwindow/pubspec.lock, bitwindow/pubspec.yaml, launcher/pubspec.lock, launcher/pubspec.yaml, thunder/pubspec.lock, thunder/pubspec.yaml, zside/pubspec.lock, zside/pubspec.yaml
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /bitwindow**
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /zside**
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /bitassets**
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /bitnames**
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /launcher**
- **build(deps): bump window_manager from 0.4.3 to 0.5.0 in /thunder**
=> back to work bump

bitwindow/server/api/wallet/wallet.go, bitwindow/server/gen/cusf/mainchain/v1/wallet.pb.go
1. Avoids a network call (which we have an absolutely ridiculous amount of in bitwindow!)
2. Moves one step closer to not requiring `txindex` on the Core node
=> bitwindow: avoid calling `getrawtransaction` when listing wallet TXs

Justfile, bitassets/macos/Podfile.lock, bitnames/pubspec.lock, bitnames/pubspec.yaml, bitwindow/pubspec.lock, bitwindow/pubspec.yaml, bitwindow/server/go.mod, bitwindow/server/go.sum, faucet/pubspec.lock, faucet/pubspec.yaml, sail_ui/pubspec.lock, sail_ui/pubspec.yaml, thunder/pubspec.lock, zside/pubspec.lock, zside/pubspec.yaml
- **build(deps): bump protobuf from 4.1.0 to 4.2.0 in /bitwindow**
- **build(deps): bump file_picker from 10.2.0 to 10.3.1 in /bitwindow**
- **build(deps): bump build_runner from 2.5.4 to 2.7.0 in /faucet**
- **build(deps): bump build_runner from 2.5.4 to 2.7.0 in /bitwindow**
- **build(deps): bump go.uber.org/mock in /bitwindow/server**
- **build(deps): bump build_runner from 2.5.4 to 2.7.0 in /sail_ui**
- **build(deps): bump build_runner from 2.5.4 to 2.7.0 in /zside**
- **build(deps): bump github.com/mattn/go-sqlite3 in /bitwindow/server**
- **build(deps): bump build_runner from 2.5.4 to 2.7.0 in /bitnames**
- **multi: bump pubspec.lock**
=> bump deps: darkness is coming, cycled with lights on my bike to the office

.github/workflows/build.yml, bitwindow/scripts/download-binaries.sh, bitwindow/server/Justfile
Turns out we were swallowing build errors on CI. Not good!
=> bitwindow: fix macos x86 builds, error on CI failures

bitwindow/server/engines/bitcoind_engine.go, bitwindow/server/engines/zmq_engine.go, bitwindow/server/main.go
Avoid taking down the entire system. Run a bunch of attempts, and sleep in between.
=> bitwindow: more error tolerant ZMQ engine startup
